#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 33
#define LARGE_STATE_COUNT 31
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 3

enum ts_symbol_identifiers {
  anon_sym_SLASH = 1,
  anon_sym_announce = 2,
  anon_sym_DOLLAR_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_DQUOTE = 5,
  anon_sym_SQUOTE = 6,
  anon_sym_BQUOTE = 7,
  anon_sym_COMMA = 8,
  anon_sym_DOT = 9,
  anon_sym_SEMI = 10,
  anon_sym_LBRACK = 11,
  anon_sym_RBRACK = 12,
  anon_sym_BANG = 13,
  anon_sym_AT = 14,
  anon_sym_POUND = 15,
  anon_sym_DOLLAR = 16,
  anon_sym_PERCENT = 17,
  anon_sym_CARET = 18,
  anon_sym_AMP = 19,
  anon_sym_STAR = 20,
  anon_sym_LPAREN = 21,
  anon_sym_DASH = 22,
  anon_sym__ = 23,
  anon_sym_EQ = 24,
  anon_sym_PLUS = 25,
  anon_sym_LT = 26,
  anon_sym_GT = 27,
  anon_sym_QMARK = 28,
  anon_sym_COLON = 29,
  anon_sym_BSLASH = 30,
  anon_sym_LBRACE = 31,
  anon_sym_RBRACE = 32,
  sym_alnum = 33,
  aux_sym_identifier_token1 = 34,
  aux_sym_identifier_token2 = 35,
  sym_input = 36,
  sym_command = 37,
  sym__expression = 38,
  sym_variable = 39,
  sym_function = 40,
  sym_parameter = 41,
  sym_identifier = 42,
  aux_sym_input_repeat1 = 43,
  aux_sym__expression_repeat1 = 44,
  aux_sym_function_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SLASH] = "/",
  [anon_sym_announce] = "announce",
  [anon_sym_DOLLAR_LPAREN] = "$(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOT] = ".",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_BANG] = "!",
  [anon_sym_AT] = "@",
  [anon_sym_POUND] = "#",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_PERCENT] = "%",
  [anon_sym_CARET] = "^",
  [anon_sym_AMP] = "&",
  [anon_sym_STAR] = "*",
  [anon_sym_LPAREN] = "(",
  [anon_sym_DASH] = "-",
  [anon_sym__] = "_",
  [anon_sym_EQ] = "=",
  [anon_sym_PLUS] = "+",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_QMARK] = "\?",
  [anon_sym_COLON] = ":",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_alnum] = "alnum",
  [aux_sym_identifier_token1] = "identifier_token1",
  [aux_sym_identifier_token2] = "identifier_token2",
  [sym_input] = "input",
  [sym_command] = "command",
  [sym__expression] = "_expression",
  [sym_variable] = "variable",
  [sym_function] = "function",
  [sym_parameter] = "parameter",
  [sym_identifier] = "identifier",
  [aux_sym_input_repeat1] = "input_repeat1",
  [aux_sym__expression_repeat1] = "_expression_repeat1",
  [aux_sym_function_repeat1] = "function_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_announce] = anon_sym_announce,
  [anon_sym_DOLLAR_LPAREN] = anon_sym_DOLLAR_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym__] = anon_sym__,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_alnum] = sym_alnum,
  [aux_sym_identifier_token1] = aux_sym_identifier_token1,
  [aux_sym_identifier_token2] = aux_sym_identifier_token2,
  [sym_input] = sym_input,
  [sym_command] = sym_command,
  [sym__expression] = sym__expression,
  [sym_variable] = sym_variable,
  [sym_function] = sym_function,
  [sym_parameter] = sym_parameter,
  [sym_identifier] = sym_identifier,
  [aux_sym_input_repeat1] = aux_sym_input_repeat1,
  [aux_sym__expression_repeat1] = aux_sym__expression_repeat1,
  [aux_sym_function_repeat1] = aux_sym_function_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_announce] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_alnum] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifier_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_input] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_input_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_parameters = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_parameters] = "parameters",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 1},
    {field_parameters, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      ADVANCE_MAP(
        '!', 16,
        '"', 8,
        '#', 18,
        '$', 19,
        '%', 20,
        '&', 22,
        '\'', 9,
        '(', 24,
        ')', 7,
        '*', 23,
        '+', 28,
        ',', 11,
        '-', 25,
        '.', 12,
        '/', 4,
        ':', 32,
        ';', 13,
        '<', 29,
        '=', 27,
        '>', 30,
        '?', 31,
        '@', 17,
        '[', 14,
        '\\', 33,
        ']', 15,
        '^', 21,
        '_', 26,
        '`', 10,
        'a', 40,
        '{', 34,
        '}', 35,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      if (('b' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(44);
      END_STATE();
    case 1:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 2:
      if (eof) ADVANCE(3);
      ADVANCE_MAP(
        '!', 16,
        '"', 8,
        '#', 18,
        '$', 19,
        '%', 20,
        '&', 22,
        '\'', 9,
        '(', 24,
        ')', 7,
        '*', 23,
        '+', 28,
        ',', 11,
        '-', 25,
        '.', 12,
        '/', 4,
        ':', 32,
        ';', 13,
        '<', 29,
        '=', 27,
        '>', 30,
        '?', 31,
        '@', 17,
        '[', 14,
        '\\', 33,
        ']', 15,
        '^', 21,
        '_', 26,
        '`', 10,
        '{', 34,
        '}', 35,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(44);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_announce);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(44);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LPAREN);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (lookahead == '(') ADVANCE(6);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym__);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_alnum);
      if (lookahead == 'c') ADVANCE(37);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(44);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_alnum);
      if (lookahead == 'e') ADVANCE(5);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(44);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_alnum);
      if (lookahead == 'n') ADVANCE(41);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(44);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_alnum);
      if (lookahead == 'n') ADVANCE(36);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(44);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_alnum);
      if (lookahead == 'n') ADVANCE(38);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(44);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_alnum);
      if (lookahead == 'o') ADVANCE(42);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(44);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_alnum);
      if (lookahead == 'u') ADVANCE(39);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(44);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_alnum);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_alnum);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_identifier_token2);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 2},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_announce] = ACTIONS(1),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_alnum] = ACTIONS(1),
    [aux_sym_identifier_token1] = ACTIONS(1),
    [aux_sym_identifier_token2] = ACTIONS(1),
  },
  [1] = {
    [sym_input] = STATE(32),
    [sym_command] = STATE(7),
    [sym__expression] = STATE(8),
    [sym_variable] = STATE(19),
    [sym_function] = STATE(19),
    [sym_identifier] = STATE(19),
    [aux_sym_input_repeat1] = STATE(8),
    [aux_sym__expression_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_SLASH] = ACTIONS(5),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_alnum] = ACTIONS(13),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [2] = {
    [sym__expression] = STATE(26),
    [sym_variable] = STATE(19),
    [sym_function] = STATE(19),
    [sym_parameter] = STATE(4),
    [sym_identifier] = STATE(19),
    [aux_sym__expression_repeat1] = STATE(17),
    [aux_sym_function_repeat1] = STATE(4),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(17),
    [anon_sym_DQUOTE] = ACTIONS(19),
    [anon_sym_SQUOTE] = ACTIONS(21),
    [anon_sym_BQUOTE] = ACTIONS(23),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_alnum] = ACTIONS(13),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [3] = {
    [sym__expression] = STATE(3),
    [sym_variable] = STATE(19),
    [sym_function] = STATE(19),
    [sym_identifier] = STATE(19),
    [aux_sym_input_repeat1] = STATE(3),
    [aux_sym__expression_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(30),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [anon_sym_SQUOTE] = ACTIONS(27),
    [anon_sym_BQUOTE] = ACTIONS(25),
    [anon_sym_COMMA] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_POUND] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(33),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(33),
    [anon_sym__] = ACTIONS(33),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_QMARK] = ACTIONS(27),
    [anon_sym_COLON] = ACTIONS(27),
    [anon_sym_BSLASH] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(27),
    [sym_alnum] = ACTIONS(36),
    [aux_sym_identifier_token1] = ACTIONS(39),
    [aux_sym_identifier_token2] = ACTIONS(39),
  },
  [4] = {
    [sym__expression] = STATE(26),
    [sym_variable] = STATE(19),
    [sym_function] = STATE(19),
    [sym_parameter] = STATE(5),
    [sym_identifier] = STATE(19),
    [aux_sym__expression_repeat1] = STATE(17),
    [aux_sym_function_repeat1] = STATE(5),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(42),
    [anon_sym_DQUOTE] = ACTIONS(19),
    [anon_sym_SQUOTE] = ACTIONS(21),
    [anon_sym_BQUOTE] = ACTIONS(23),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_alnum] = ACTIONS(13),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [5] = {
    [sym__expression] = STATE(26),
    [sym_variable] = STATE(19),
    [sym_function] = STATE(19),
    [sym_parameter] = STATE(5),
    [sym_identifier] = STATE(19),
    [aux_sym__expression_repeat1] = STATE(17),
    [aux_sym_function_repeat1] = STATE(5),
    [anon_sym_SLASH] = ACTIONS(44),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(47),
    [anon_sym_RPAREN] = ACTIONS(44),
    [anon_sym_DQUOTE] = ACTIONS(50),
    [anon_sym_SQUOTE] = ACTIONS(53),
    [anon_sym_BQUOTE] = ACTIONS(56),
    [anon_sym_COMMA] = ACTIONS(44),
    [anon_sym_DOT] = ACTIONS(44),
    [anon_sym_SEMI] = ACTIONS(44),
    [anon_sym_LBRACK] = ACTIONS(44),
    [anon_sym_RBRACK] = ACTIONS(44),
    [anon_sym_BANG] = ACTIONS(44),
    [anon_sym_AT] = ACTIONS(44),
    [anon_sym_POUND] = ACTIONS(44),
    [anon_sym_DOLLAR] = ACTIONS(59),
    [anon_sym_PERCENT] = ACTIONS(44),
    [anon_sym_CARET] = ACTIONS(44),
    [anon_sym_AMP] = ACTIONS(44),
    [anon_sym_STAR] = ACTIONS(44),
    [anon_sym_LPAREN] = ACTIONS(44),
    [anon_sym_DASH] = ACTIONS(59),
    [anon_sym__] = ACTIONS(59),
    [anon_sym_EQ] = ACTIONS(44),
    [anon_sym_PLUS] = ACTIONS(44),
    [anon_sym_LT] = ACTIONS(44),
    [anon_sym_GT] = ACTIONS(44),
    [anon_sym_QMARK] = ACTIONS(44),
    [anon_sym_COLON] = ACTIONS(44),
    [anon_sym_BSLASH] = ACTIONS(44),
    [anon_sym_LBRACE] = ACTIONS(44),
    [anon_sym_RBRACE] = ACTIONS(44),
    [sym_alnum] = ACTIONS(62),
    [aux_sym_identifier_token1] = ACTIONS(65),
    [aux_sym_identifier_token2] = ACTIONS(65),
  },
  [6] = {
    [sym__expression] = STATE(3),
    [sym_variable] = STATE(19),
    [sym_function] = STATE(19),
    [sym_identifier] = STATE(19),
    [aux_sym_input_repeat1] = STATE(3),
    [aux_sym__expression_repeat1] = STATE(17),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(68),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_alnum] = ACTIONS(13),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [7] = {
    [sym__expression] = STATE(10),
    [sym_variable] = STATE(19),
    [sym_function] = STATE(19),
    [sym_identifier] = STATE(19),
    [aux_sym_input_repeat1] = STATE(10),
    [aux_sym__expression_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(70),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_alnum] = ACTIONS(13),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [8] = {
    [sym__expression] = STATE(3),
    [sym_variable] = STATE(19),
    [sym_function] = STATE(19),
    [sym_identifier] = STATE(19),
    [aux_sym_input_repeat1] = STATE(3),
    [aux_sym__expression_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(70),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_alnum] = ACTIONS(13),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [9] = {
    [sym__expression] = STATE(12),
    [sym_variable] = STATE(19),
    [sym_function] = STATE(19),
    [sym_identifier] = STATE(19),
    [aux_sym_input_repeat1] = STATE(12),
    [aux_sym__expression_repeat1] = STATE(17),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(72),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_alnum] = ACTIONS(13),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [10] = {
    [sym__expression] = STATE(3),
    [sym_variable] = STATE(19),
    [sym_function] = STATE(19),
    [sym_identifier] = STATE(19),
    [aux_sym_input_repeat1] = STATE(3),
    [aux_sym__expression_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(74),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_alnum] = ACTIONS(13),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [11] = {
    [sym__expression] = STATE(6),
    [sym_variable] = STATE(19),
    [sym_function] = STATE(19),
    [sym_identifier] = STATE(19),
    [aux_sym_input_repeat1] = STATE(6),
    [aux_sym__expression_repeat1] = STATE(17),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(72),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_alnum] = ACTIONS(13),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [12] = {
    [sym__expression] = STATE(3),
    [sym_variable] = STATE(19),
    [sym_function] = STATE(19),
    [sym_identifier] = STATE(19),
    [aux_sym_input_repeat1] = STATE(3),
    [aux_sym__expression_repeat1] = STATE(17),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(68),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_alnum] = ACTIONS(13),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [13] = {
    [sym__expression] = STATE(14),
    [sym_variable] = STATE(19),
    [sym_function] = STATE(19),
    [sym_identifier] = STATE(19),
    [aux_sym_input_repeat1] = STATE(14),
    [aux_sym__expression_repeat1] = STATE(17),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(76),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_alnum] = ACTIONS(13),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [14] = {
    [sym__expression] = STATE(3),
    [sym_variable] = STATE(19),
    [sym_function] = STATE(19),
    [sym_identifier] = STATE(19),
    [aux_sym_input_repeat1] = STATE(3),
    [aux_sym__expression_repeat1] = STATE(17),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(78),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_alnum] = ACTIONS(13),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [15] = {
    [aux_sym__expression_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(80),
    [anon_sym_SLASH] = ACTIONS(82),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(80),
    [anon_sym_RPAREN] = ACTIONS(82),
    [anon_sym_DQUOTE] = ACTIONS(80),
    [anon_sym_SQUOTE] = ACTIONS(82),
    [anon_sym_BQUOTE] = ACTIONS(80),
    [anon_sym_COMMA] = ACTIONS(82),
    [anon_sym_DOT] = ACTIONS(82),
    [anon_sym_SEMI] = ACTIONS(82),
    [anon_sym_LBRACK] = ACTIONS(82),
    [anon_sym_RBRACK] = ACTIONS(82),
    [anon_sym_BANG] = ACTIONS(82),
    [anon_sym_AT] = ACTIONS(82),
    [anon_sym_POUND] = ACTIONS(82),
    [anon_sym_DOLLAR] = ACTIONS(84),
    [anon_sym_PERCENT] = ACTIONS(82),
    [anon_sym_CARET] = ACTIONS(82),
    [anon_sym_AMP] = ACTIONS(82),
    [anon_sym_STAR] = ACTIONS(82),
    [anon_sym_LPAREN] = ACTIONS(82),
    [anon_sym_DASH] = ACTIONS(84),
    [anon_sym__] = ACTIONS(84),
    [anon_sym_EQ] = ACTIONS(82),
    [anon_sym_PLUS] = ACTIONS(82),
    [anon_sym_LT] = ACTIONS(82),
    [anon_sym_GT] = ACTIONS(82),
    [anon_sym_QMARK] = ACTIONS(82),
    [anon_sym_COLON] = ACTIONS(82),
    [anon_sym_BSLASH] = ACTIONS(82),
    [anon_sym_LBRACE] = ACTIONS(82),
    [anon_sym_RBRACE] = ACTIONS(82),
    [sym_alnum] = ACTIONS(86),
    [aux_sym_identifier_token1] = ACTIONS(86),
    [aux_sym_identifier_token2] = ACTIONS(86),
  },
  [16] = {
    [aux_sym__expression_repeat1] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(80),
    [anon_sym_SLASH] = ACTIONS(88),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(80),
    [anon_sym_RPAREN] = ACTIONS(88),
    [anon_sym_DQUOTE] = ACTIONS(80),
    [anon_sym_SQUOTE] = ACTIONS(88),
    [anon_sym_BQUOTE] = ACTIONS(80),
    [anon_sym_COMMA] = ACTIONS(88),
    [anon_sym_DOT] = ACTIONS(88),
    [anon_sym_SEMI] = ACTIONS(88),
    [anon_sym_LBRACK] = ACTIONS(88),
    [anon_sym_RBRACK] = ACTIONS(88),
    [anon_sym_BANG] = ACTIONS(88),
    [anon_sym_AT] = ACTIONS(88),
    [anon_sym_POUND] = ACTIONS(88),
    [anon_sym_DOLLAR] = ACTIONS(90),
    [anon_sym_PERCENT] = ACTIONS(88),
    [anon_sym_CARET] = ACTIONS(88),
    [anon_sym_AMP] = ACTIONS(88),
    [anon_sym_STAR] = ACTIONS(88),
    [anon_sym_LPAREN] = ACTIONS(88),
    [anon_sym_DASH] = ACTIONS(90),
    [anon_sym__] = ACTIONS(90),
    [anon_sym_EQ] = ACTIONS(88),
    [anon_sym_PLUS] = ACTIONS(88),
    [anon_sym_LT] = ACTIONS(88),
    [anon_sym_GT] = ACTIONS(88),
    [anon_sym_QMARK] = ACTIONS(88),
    [anon_sym_COLON] = ACTIONS(88),
    [anon_sym_BSLASH] = ACTIONS(88),
    [anon_sym_LBRACE] = ACTIONS(88),
    [anon_sym_RBRACE] = ACTIONS(88),
    [sym_alnum] = ACTIONS(86),
    [aux_sym_identifier_token1] = ACTIONS(86),
    [aux_sym_identifier_token2] = ACTIONS(86),
  },
  [17] = {
    [sym_variable] = STATE(16),
    [sym_function] = STATE(16),
    [sym_identifier] = STATE(16),
    [aux_sym__expression_repeat1] = STATE(18),
    [anon_sym_SLASH] = ACTIONS(82),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(82),
    [anon_sym_SQUOTE] = ACTIONS(82),
    [anon_sym_COMMA] = ACTIONS(82),
    [anon_sym_DOT] = ACTIONS(82),
    [anon_sym_SEMI] = ACTIONS(82),
    [anon_sym_LBRACK] = ACTIONS(82),
    [anon_sym_RBRACK] = ACTIONS(82),
    [anon_sym_BANG] = ACTIONS(82),
    [anon_sym_AT] = ACTIONS(82),
    [anon_sym_POUND] = ACTIONS(82),
    [anon_sym_DOLLAR] = ACTIONS(84),
    [anon_sym_PERCENT] = ACTIONS(82),
    [anon_sym_CARET] = ACTIONS(82),
    [anon_sym_AMP] = ACTIONS(82),
    [anon_sym_STAR] = ACTIONS(82),
    [anon_sym_LPAREN] = ACTIONS(82),
    [anon_sym_DASH] = ACTIONS(84),
    [anon_sym__] = ACTIONS(84),
    [anon_sym_EQ] = ACTIONS(82),
    [anon_sym_PLUS] = ACTIONS(82),
    [anon_sym_LT] = ACTIONS(82),
    [anon_sym_GT] = ACTIONS(82),
    [anon_sym_QMARK] = ACTIONS(82),
    [anon_sym_COLON] = ACTIONS(82),
    [anon_sym_BSLASH] = ACTIONS(82),
    [anon_sym_LBRACE] = ACTIONS(82),
    [anon_sym_RBRACE] = ACTIONS(82),
    [sym_alnum] = ACTIONS(92),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [18] = {
    [aux_sym__expression_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(94),
    [anon_sym_SLASH] = ACTIONS(96),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(94),
    [anon_sym_RPAREN] = ACTIONS(96),
    [anon_sym_DQUOTE] = ACTIONS(94),
    [anon_sym_SQUOTE] = ACTIONS(96),
    [anon_sym_BQUOTE] = ACTIONS(94),
    [anon_sym_COMMA] = ACTIONS(96),
    [anon_sym_DOT] = ACTIONS(96),
    [anon_sym_SEMI] = ACTIONS(96),
    [anon_sym_LBRACK] = ACTIONS(96),
    [anon_sym_RBRACK] = ACTIONS(96),
    [anon_sym_BANG] = ACTIONS(96),
    [anon_sym_AT] = ACTIONS(96),
    [anon_sym_POUND] = ACTIONS(96),
    [anon_sym_DOLLAR] = ACTIONS(99),
    [anon_sym_PERCENT] = ACTIONS(96),
    [anon_sym_CARET] = ACTIONS(96),
    [anon_sym_AMP] = ACTIONS(96),
    [anon_sym_STAR] = ACTIONS(96),
    [anon_sym_LPAREN] = ACTIONS(96),
    [anon_sym_DASH] = ACTIONS(99),
    [anon_sym__] = ACTIONS(99),
    [anon_sym_EQ] = ACTIONS(96),
    [anon_sym_PLUS] = ACTIONS(96),
    [anon_sym_LT] = ACTIONS(96),
    [anon_sym_GT] = ACTIONS(96),
    [anon_sym_QMARK] = ACTIONS(96),
    [anon_sym_COLON] = ACTIONS(96),
    [anon_sym_BSLASH] = ACTIONS(96),
    [anon_sym_LBRACE] = ACTIONS(96),
    [anon_sym_RBRACE] = ACTIONS(96),
    [sym_alnum] = ACTIONS(102),
    [aux_sym_identifier_token1] = ACTIONS(102),
    [aux_sym_identifier_token2] = ACTIONS(102),
  },
  [19] = {
    [aux_sym__expression_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(104),
    [anon_sym_SLASH] = ACTIONS(106),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(104),
    [anon_sym_RPAREN] = ACTIONS(106),
    [anon_sym_DQUOTE] = ACTIONS(104),
    [anon_sym_SQUOTE] = ACTIONS(106),
    [anon_sym_BQUOTE] = ACTIONS(104),
    [anon_sym_COMMA] = ACTIONS(106),
    [anon_sym_DOT] = ACTIONS(106),
    [anon_sym_SEMI] = ACTIONS(106),
    [anon_sym_LBRACK] = ACTIONS(106),
    [anon_sym_RBRACK] = ACTIONS(106),
    [anon_sym_BANG] = ACTIONS(106),
    [anon_sym_AT] = ACTIONS(106),
    [anon_sym_POUND] = ACTIONS(106),
    [anon_sym_DOLLAR] = ACTIONS(108),
    [anon_sym_PERCENT] = ACTIONS(106),
    [anon_sym_CARET] = ACTIONS(106),
    [anon_sym_AMP] = ACTIONS(106),
    [anon_sym_STAR] = ACTIONS(106),
    [anon_sym_LPAREN] = ACTIONS(106),
    [anon_sym_DASH] = ACTIONS(108),
    [anon_sym__] = ACTIONS(108),
    [anon_sym_EQ] = ACTIONS(106),
    [anon_sym_PLUS] = ACTIONS(106),
    [anon_sym_LT] = ACTIONS(106),
    [anon_sym_GT] = ACTIONS(106),
    [anon_sym_QMARK] = ACTIONS(106),
    [anon_sym_COLON] = ACTIONS(106),
    [anon_sym_BSLASH] = ACTIONS(106),
    [anon_sym_LBRACE] = ACTIONS(106),
    [anon_sym_RBRACE] = ACTIONS(106),
    [sym_alnum] = ACTIONS(110),
    [aux_sym_identifier_token1] = ACTIONS(110),
    [aux_sym_identifier_token2] = ACTIONS(110),
  },
  [20] = {
    [aux_sym__expression_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(112),
    [anon_sym_SLASH] = ACTIONS(82),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(112),
    [anon_sym_RPAREN] = ACTIONS(82),
    [anon_sym_DQUOTE] = ACTIONS(112),
    [anon_sym_SQUOTE] = ACTIONS(82),
    [anon_sym_BQUOTE] = ACTIONS(112),
    [anon_sym_COMMA] = ACTIONS(82),
    [anon_sym_DOT] = ACTIONS(82),
    [anon_sym_SEMI] = ACTIONS(82),
    [anon_sym_LBRACK] = ACTIONS(82),
    [anon_sym_RBRACK] = ACTIONS(82),
    [anon_sym_BANG] = ACTIONS(82),
    [anon_sym_AT] = ACTIONS(82),
    [anon_sym_POUND] = ACTIONS(82),
    [anon_sym_DOLLAR] = ACTIONS(84),
    [anon_sym_PERCENT] = ACTIONS(82),
    [anon_sym_CARET] = ACTIONS(82),
    [anon_sym_AMP] = ACTIONS(82),
    [anon_sym_STAR] = ACTIONS(82),
    [anon_sym_LPAREN] = ACTIONS(82),
    [anon_sym_DASH] = ACTIONS(84),
    [anon_sym__] = ACTIONS(84),
    [anon_sym_EQ] = ACTIONS(82),
    [anon_sym_PLUS] = ACTIONS(82),
    [anon_sym_LT] = ACTIONS(82),
    [anon_sym_GT] = ACTIONS(82),
    [anon_sym_QMARK] = ACTIONS(82),
    [anon_sym_COLON] = ACTIONS(82),
    [anon_sym_BSLASH] = ACTIONS(82),
    [anon_sym_LBRACE] = ACTIONS(82),
    [anon_sym_RBRACE] = ACTIONS(82),
    [sym_alnum] = ACTIONS(114),
    [aux_sym_identifier_token1] = ACTIONS(114),
    [aux_sym_identifier_token2] = ACTIONS(114),
  },
  [21] = {
    [ts_builtin_sym_end] = ACTIONS(116),
    [anon_sym_SLASH] = ACTIONS(116),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(116),
    [anon_sym_RPAREN] = ACTIONS(116),
    [anon_sym_DQUOTE] = ACTIONS(116),
    [anon_sym_SQUOTE] = ACTIONS(116),
    [anon_sym_BQUOTE] = ACTIONS(116),
    [anon_sym_COMMA] = ACTIONS(116),
    [anon_sym_DOT] = ACTIONS(116),
    [anon_sym_SEMI] = ACTIONS(116),
    [anon_sym_LBRACK] = ACTIONS(116),
    [anon_sym_RBRACK] = ACTIONS(116),
    [anon_sym_BANG] = ACTIONS(116),
    [anon_sym_AT] = ACTIONS(116),
    [anon_sym_POUND] = ACTIONS(116),
    [anon_sym_DOLLAR] = ACTIONS(118),
    [anon_sym_PERCENT] = ACTIONS(116),
    [anon_sym_CARET] = ACTIONS(116),
    [anon_sym_AMP] = ACTIONS(116),
    [anon_sym_STAR] = ACTIONS(116),
    [anon_sym_LPAREN] = ACTIONS(116),
    [anon_sym_DASH] = ACTIONS(118),
    [anon_sym__] = ACTIONS(118),
    [anon_sym_EQ] = ACTIONS(116),
    [anon_sym_PLUS] = ACTIONS(116),
    [anon_sym_LT] = ACTIONS(116),
    [anon_sym_GT] = ACTIONS(116),
    [anon_sym_QMARK] = ACTIONS(116),
    [anon_sym_COLON] = ACTIONS(116),
    [anon_sym_BSLASH] = ACTIONS(116),
    [anon_sym_LBRACE] = ACTIONS(116),
    [anon_sym_RBRACE] = ACTIONS(116),
    [sym_alnum] = ACTIONS(118),
    [aux_sym_identifier_token1] = ACTIONS(118),
    [aux_sym_identifier_token2] = ACTIONS(118),
  },
  [22] = {
    [ts_builtin_sym_end] = ACTIONS(120),
    [anon_sym_SLASH] = ACTIONS(120),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(120),
    [anon_sym_RPAREN] = ACTIONS(120),
    [anon_sym_DQUOTE] = ACTIONS(120),
    [anon_sym_SQUOTE] = ACTIONS(120),
    [anon_sym_BQUOTE] = ACTIONS(120),
    [anon_sym_COMMA] = ACTIONS(120),
    [anon_sym_DOT] = ACTIONS(120),
    [anon_sym_SEMI] = ACTIONS(120),
    [anon_sym_LBRACK] = ACTIONS(120),
    [anon_sym_RBRACK] = ACTIONS(120),
    [anon_sym_BANG] = ACTIONS(120),
    [anon_sym_AT] = ACTIONS(120),
    [anon_sym_POUND] = ACTIONS(120),
    [anon_sym_DOLLAR] = ACTIONS(122),
    [anon_sym_PERCENT] = ACTIONS(120),
    [anon_sym_CARET] = ACTIONS(120),
    [anon_sym_AMP] = ACTIONS(120),
    [anon_sym_STAR] = ACTIONS(120),
    [anon_sym_LPAREN] = ACTIONS(120),
    [anon_sym_DASH] = ACTIONS(122),
    [anon_sym__] = ACTIONS(122),
    [anon_sym_EQ] = ACTIONS(120),
    [anon_sym_PLUS] = ACTIONS(120),
    [anon_sym_LT] = ACTIONS(120),
    [anon_sym_GT] = ACTIONS(120),
    [anon_sym_QMARK] = ACTIONS(120),
    [anon_sym_COLON] = ACTIONS(120),
    [anon_sym_BSLASH] = ACTIONS(120),
    [anon_sym_LBRACE] = ACTIONS(120),
    [anon_sym_RBRACE] = ACTIONS(120),
    [sym_alnum] = ACTIONS(122),
    [aux_sym_identifier_token1] = ACTIONS(122),
    [aux_sym_identifier_token2] = ACTIONS(122),
  },
  [23] = {
    [ts_builtin_sym_end] = ACTIONS(124),
    [anon_sym_SLASH] = ACTIONS(124),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(124),
    [anon_sym_RPAREN] = ACTIONS(124),
    [anon_sym_DQUOTE] = ACTIONS(124),
    [anon_sym_SQUOTE] = ACTIONS(124),
    [anon_sym_BQUOTE] = ACTIONS(124),
    [anon_sym_COMMA] = ACTIONS(124),
    [anon_sym_DOT] = ACTIONS(124),
    [anon_sym_SEMI] = ACTIONS(124),
    [anon_sym_LBRACK] = ACTIONS(124),
    [anon_sym_RBRACK] = ACTIONS(124),
    [anon_sym_BANG] = ACTIONS(124),
    [anon_sym_AT] = ACTIONS(124),
    [anon_sym_POUND] = ACTIONS(124),
    [anon_sym_DOLLAR] = ACTIONS(126),
    [anon_sym_PERCENT] = ACTIONS(124),
    [anon_sym_CARET] = ACTIONS(124),
    [anon_sym_AMP] = ACTIONS(124),
    [anon_sym_STAR] = ACTIONS(124),
    [anon_sym_LPAREN] = ACTIONS(124),
    [anon_sym_DASH] = ACTIONS(126),
    [anon_sym__] = ACTIONS(126),
    [anon_sym_EQ] = ACTIONS(124),
    [anon_sym_PLUS] = ACTIONS(124),
    [anon_sym_LT] = ACTIONS(124),
    [anon_sym_GT] = ACTIONS(124),
    [anon_sym_QMARK] = ACTIONS(124),
    [anon_sym_COLON] = ACTIONS(124),
    [anon_sym_BSLASH] = ACTIONS(124),
    [anon_sym_LBRACE] = ACTIONS(124),
    [anon_sym_RBRACE] = ACTIONS(124),
    [sym_alnum] = ACTIONS(126),
    [aux_sym_identifier_token1] = ACTIONS(126),
    [aux_sym_identifier_token2] = ACTIONS(126),
  },
  [24] = {
    [anon_sym_SLASH] = ACTIONS(128),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(128),
    [anon_sym_RPAREN] = ACTIONS(128),
    [anon_sym_DQUOTE] = ACTIONS(128),
    [anon_sym_SQUOTE] = ACTIONS(128),
    [anon_sym_BQUOTE] = ACTIONS(128),
    [anon_sym_COMMA] = ACTIONS(128),
    [anon_sym_DOT] = ACTIONS(128),
    [anon_sym_SEMI] = ACTIONS(128),
    [anon_sym_LBRACK] = ACTIONS(128),
    [anon_sym_RBRACK] = ACTIONS(128),
    [anon_sym_BANG] = ACTIONS(128),
    [anon_sym_AT] = ACTIONS(128),
    [anon_sym_POUND] = ACTIONS(128),
    [anon_sym_DOLLAR] = ACTIONS(130),
    [anon_sym_PERCENT] = ACTIONS(128),
    [anon_sym_CARET] = ACTIONS(128),
    [anon_sym_AMP] = ACTIONS(128),
    [anon_sym_STAR] = ACTIONS(128),
    [anon_sym_LPAREN] = ACTIONS(128),
    [anon_sym_DASH] = ACTIONS(130),
    [anon_sym__] = ACTIONS(130),
    [anon_sym_EQ] = ACTIONS(128),
    [anon_sym_PLUS] = ACTIONS(128),
    [anon_sym_LT] = ACTIONS(128),
    [anon_sym_GT] = ACTIONS(128),
    [anon_sym_QMARK] = ACTIONS(128),
    [anon_sym_COLON] = ACTIONS(128),
    [anon_sym_BSLASH] = ACTIONS(128),
    [anon_sym_LBRACE] = ACTIONS(128),
    [anon_sym_RBRACE] = ACTIONS(128),
    [sym_alnum] = ACTIONS(130),
    [aux_sym_identifier_token1] = ACTIONS(130),
    [aux_sym_identifier_token2] = ACTIONS(130),
  },
  [25] = {
    [anon_sym_SLASH] = ACTIONS(128),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(128),
    [anon_sym_RPAREN] = ACTIONS(128),
    [anon_sym_DQUOTE] = ACTIONS(128),
    [anon_sym_SQUOTE] = ACTIONS(128),
    [anon_sym_BQUOTE] = ACTIONS(128),
    [anon_sym_COMMA] = ACTIONS(128),
    [anon_sym_DOT] = ACTIONS(128),
    [anon_sym_SEMI] = ACTIONS(128),
    [anon_sym_LBRACK] = ACTIONS(128),
    [anon_sym_RBRACK] = ACTIONS(128),
    [anon_sym_BANG] = ACTIONS(128),
    [anon_sym_AT] = ACTIONS(128),
    [anon_sym_POUND] = ACTIONS(128),
    [anon_sym_DOLLAR] = ACTIONS(130),
    [anon_sym_PERCENT] = ACTIONS(128),
    [anon_sym_CARET] = ACTIONS(128),
    [anon_sym_AMP] = ACTIONS(128),
    [anon_sym_STAR] = ACTIONS(128),
    [anon_sym_LPAREN] = ACTIONS(128),
    [anon_sym_DASH] = ACTIONS(130),
    [anon_sym__] = ACTIONS(130),
    [anon_sym_EQ] = ACTIONS(128),
    [anon_sym_PLUS] = ACTIONS(128),
    [anon_sym_LT] = ACTIONS(128),
    [anon_sym_GT] = ACTIONS(128),
    [anon_sym_QMARK] = ACTIONS(128),
    [anon_sym_COLON] = ACTIONS(128),
    [anon_sym_BSLASH] = ACTIONS(128),
    [anon_sym_LBRACE] = ACTIONS(128),
    [anon_sym_RBRACE] = ACTIONS(128),
    [sym_alnum] = ACTIONS(130),
    [aux_sym_identifier_token1] = ACTIONS(130),
    [aux_sym_identifier_token2] = ACTIONS(130),
  },
  [26] = {
    [anon_sym_SLASH] = ACTIONS(132),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(132),
    [anon_sym_RPAREN] = ACTIONS(132),
    [anon_sym_DQUOTE] = ACTIONS(132),
    [anon_sym_SQUOTE] = ACTIONS(132),
    [anon_sym_BQUOTE] = ACTIONS(132),
    [anon_sym_COMMA] = ACTIONS(132),
    [anon_sym_DOT] = ACTIONS(132),
    [anon_sym_SEMI] = ACTIONS(132),
    [anon_sym_LBRACK] = ACTIONS(132),
    [anon_sym_RBRACK] = ACTIONS(132),
    [anon_sym_BANG] = ACTIONS(132),
    [anon_sym_AT] = ACTIONS(132),
    [anon_sym_POUND] = ACTIONS(132),
    [anon_sym_DOLLAR] = ACTIONS(134),
    [anon_sym_PERCENT] = ACTIONS(132),
    [anon_sym_CARET] = ACTIONS(132),
    [anon_sym_AMP] = ACTIONS(132),
    [anon_sym_STAR] = ACTIONS(132),
    [anon_sym_LPAREN] = ACTIONS(132),
    [anon_sym_DASH] = ACTIONS(134),
    [anon_sym__] = ACTIONS(134),
    [anon_sym_EQ] = ACTIONS(132),
    [anon_sym_PLUS] = ACTIONS(132),
    [anon_sym_LT] = ACTIONS(132),
    [anon_sym_GT] = ACTIONS(132),
    [anon_sym_QMARK] = ACTIONS(132),
    [anon_sym_COLON] = ACTIONS(132),
    [anon_sym_BSLASH] = ACTIONS(132),
    [anon_sym_LBRACE] = ACTIONS(132),
    [anon_sym_RBRACE] = ACTIONS(132),
    [sym_alnum] = ACTIONS(134),
    [aux_sym_identifier_token1] = ACTIONS(134),
    [aux_sym_identifier_token2] = ACTIONS(134),
  },
  [27] = {
    [anon_sym_SLASH] = ACTIONS(136),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(136),
    [anon_sym_RPAREN] = ACTIONS(136),
    [anon_sym_DQUOTE] = ACTIONS(136),
    [anon_sym_SQUOTE] = ACTIONS(136),
    [anon_sym_BQUOTE] = ACTIONS(136),
    [anon_sym_COMMA] = ACTIONS(136),
    [anon_sym_DOT] = ACTIONS(136),
    [anon_sym_SEMI] = ACTIONS(136),
    [anon_sym_LBRACK] = ACTIONS(136),
    [anon_sym_RBRACK] = ACTIONS(136),
    [anon_sym_BANG] = ACTIONS(136),
    [anon_sym_AT] = ACTIONS(136),
    [anon_sym_POUND] = ACTIONS(136),
    [anon_sym_DOLLAR] = ACTIONS(138),
    [anon_sym_PERCENT] = ACTIONS(136),
    [anon_sym_CARET] = ACTIONS(136),
    [anon_sym_AMP] = ACTIONS(136),
    [anon_sym_STAR] = ACTIONS(136),
    [anon_sym_LPAREN] = ACTIONS(136),
    [anon_sym_DASH] = ACTIONS(138),
    [anon_sym__] = ACTIONS(138),
    [anon_sym_EQ] = ACTIONS(136),
    [anon_sym_PLUS] = ACTIONS(136),
    [anon_sym_LT] = ACTIONS(136),
    [anon_sym_GT] = ACTIONS(136),
    [anon_sym_QMARK] = ACTIONS(136),
    [anon_sym_COLON] = ACTIONS(136),
    [anon_sym_BSLASH] = ACTIONS(136),
    [anon_sym_LBRACE] = ACTIONS(136),
    [anon_sym_RBRACE] = ACTIONS(136),
    [sym_alnum] = ACTIONS(138),
    [aux_sym_identifier_token1] = ACTIONS(138),
    [aux_sym_identifier_token2] = ACTIONS(138),
  },
  [28] = {
    [anon_sym_SLASH] = ACTIONS(136),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(136),
    [anon_sym_RPAREN] = ACTIONS(136),
    [anon_sym_DQUOTE] = ACTIONS(136),
    [anon_sym_SQUOTE] = ACTIONS(136),
    [anon_sym_BQUOTE] = ACTIONS(136),
    [anon_sym_COMMA] = ACTIONS(136),
    [anon_sym_DOT] = ACTIONS(136),
    [anon_sym_SEMI] = ACTIONS(136),
    [anon_sym_LBRACK] = ACTIONS(136),
    [anon_sym_RBRACK] = ACTIONS(136),
    [anon_sym_BANG] = ACTIONS(136),
    [anon_sym_AT] = ACTIONS(136),
    [anon_sym_POUND] = ACTIONS(136),
    [anon_sym_DOLLAR] = ACTIONS(138),
    [anon_sym_PERCENT] = ACTIONS(136),
    [anon_sym_CARET] = ACTIONS(136),
    [anon_sym_AMP] = ACTIONS(136),
    [anon_sym_STAR] = ACTIONS(136),
    [anon_sym_LPAREN] = ACTIONS(136),
    [anon_sym_DASH] = ACTIONS(138),
    [anon_sym__] = ACTIONS(138),
    [anon_sym_EQ] = ACTIONS(136),
    [anon_sym_PLUS] = ACTIONS(136),
    [anon_sym_LT] = ACTIONS(136),
    [anon_sym_GT] = ACTIONS(136),
    [anon_sym_QMARK] = ACTIONS(136),
    [anon_sym_COLON] = ACTIONS(136),
    [anon_sym_BSLASH] = ACTIONS(136),
    [anon_sym_LBRACE] = ACTIONS(136),
    [anon_sym_RBRACE] = ACTIONS(136),
    [sym_alnum] = ACTIONS(138),
    [aux_sym_identifier_token1] = ACTIONS(138),
    [aux_sym_identifier_token2] = ACTIONS(138),
  },
  [29] = {
    [anon_sym_SLASH] = ACTIONS(140),
    [anon_sym_announce] = ACTIONS(142),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(140),
    [anon_sym_RPAREN] = ACTIONS(140),
    [anon_sym_SQUOTE] = ACTIONS(140),
    [anon_sym_COMMA] = ACTIONS(140),
    [anon_sym_DOT] = ACTIONS(140),
    [anon_sym_SEMI] = ACTIONS(140),
    [anon_sym_LBRACK] = ACTIONS(140),
    [anon_sym_RBRACK] = ACTIONS(140),
    [anon_sym_BANG] = ACTIONS(140),
    [anon_sym_AT] = ACTIONS(140),
    [anon_sym_POUND] = ACTIONS(140),
    [anon_sym_DOLLAR] = ACTIONS(144),
    [anon_sym_PERCENT] = ACTIONS(140),
    [anon_sym_CARET] = ACTIONS(140),
    [anon_sym_AMP] = ACTIONS(140),
    [anon_sym_STAR] = ACTIONS(140),
    [anon_sym_LPAREN] = ACTIONS(140),
    [anon_sym_DASH] = ACTIONS(144),
    [anon_sym__] = ACTIONS(144),
    [anon_sym_EQ] = ACTIONS(140),
    [anon_sym_PLUS] = ACTIONS(140),
    [anon_sym_LT] = ACTIONS(140),
    [anon_sym_GT] = ACTIONS(140),
    [anon_sym_QMARK] = ACTIONS(140),
    [anon_sym_COLON] = ACTIONS(140),
    [anon_sym_BSLASH] = ACTIONS(140),
    [anon_sym_LBRACE] = ACTIONS(140),
    [anon_sym_RBRACE] = ACTIONS(140),
    [sym_alnum] = ACTIONS(144),
    [aux_sym_identifier_token1] = ACTIONS(144),
    [aux_sym_identifier_token2] = ACTIONS(144),
  },
  [30] = {
    [ts_builtin_sym_end] = ACTIONS(146),
    [anon_sym_SLASH] = ACTIONS(146),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(146),
    [anon_sym_RPAREN] = ACTIONS(146),
    [anon_sym_SQUOTE] = ACTIONS(146),
    [anon_sym_COMMA] = ACTIONS(146),
    [anon_sym_DOT] = ACTIONS(146),
    [anon_sym_SEMI] = ACTIONS(146),
    [anon_sym_LBRACK] = ACTIONS(146),
    [anon_sym_RBRACK] = ACTIONS(146),
    [anon_sym_BANG] = ACTIONS(146),
    [anon_sym_AT] = ACTIONS(146),
    [anon_sym_POUND] = ACTIONS(146),
    [anon_sym_DOLLAR] = ACTIONS(148),
    [anon_sym_PERCENT] = ACTIONS(146),
    [anon_sym_CARET] = ACTIONS(146),
    [anon_sym_AMP] = ACTIONS(146),
    [anon_sym_STAR] = ACTIONS(146),
    [anon_sym_LPAREN] = ACTIONS(146),
    [anon_sym_DASH] = ACTIONS(148),
    [anon_sym__] = ACTIONS(148),
    [anon_sym_EQ] = ACTIONS(146),
    [anon_sym_PLUS] = ACTIONS(146),
    [anon_sym_LT] = ACTIONS(146),
    [anon_sym_GT] = ACTIONS(146),
    [anon_sym_QMARK] = ACTIONS(146),
    [anon_sym_COLON] = ACTIONS(146),
    [anon_sym_BSLASH] = ACTIONS(146),
    [anon_sym_LBRACE] = ACTIONS(146),
    [anon_sym_RBRACE] = ACTIONS(146),
    [sym_alnum] = ACTIONS(148),
    [aux_sym_identifier_token1] = ACTIONS(148),
    [aux_sym_identifier_token2] = ACTIONS(148),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    STATE(2), 1,
      sym_identifier,
    ACTIONS(150), 2,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
  [8] = 1,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(31)] = 0,
  [SMALL_STATE(32)] = 8,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__expression_repeat1, 2, 0, 0),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expression_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expression_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__expression_repeat1, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 3, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, 0, 1),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 3, 0, 1),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 4, 0, 2),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 4, 0, 2),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 2, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__expression_repeat1, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__expression_repeat1, 1, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [152] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_akbs(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
