#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 45
#define LARGE_STATE_COUNT 42
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 0
#define TOKEN_COUNT 39
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 3

enum ts_symbol_identifiers {
  anon_sym_SLASH = 1,
  anon_sym_announce = 2,
  anon_sym_DOLLAR_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_DQUOTE = 5,
  anon_sym_SQUOTE = 6,
  anon_sym_BQUOTE = 7,
  anon_sym_COMMA = 8,
  anon_sym_DOT = 9,
  anon_sym_SEMI = 10,
  anon_sym_LBRACK = 11,
  anon_sym_RBRACK = 12,
  anon_sym_BANG = 13,
  anon_sym_AT = 14,
  anon_sym_POUND = 15,
  anon_sym_DOLLAR = 16,
  anon_sym_PERCENT = 17,
  anon_sym_CARET = 18,
  anon_sym_AMP = 19,
  anon_sym_STAR = 20,
  anon_sym_LPAREN = 21,
  anon_sym_DASH = 22,
  anon_sym__ = 23,
  anon_sym_EQ = 24,
  anon_sym_PLUS = 25,
  anon_sym_LT = 26,
  anon_sym_GT = 27,
  anon_sym_QMARK = 28,
  anon_sym_COLON = 29,
  anon_sym_BSLASH = 30,
  anon_sym_LBRACE = 31,
  anon_sym_RBRACE = 32,
  anon_sym_BSLASH_LPAREN = 33,
  anon_sym_BSLASH_RPAREN = 34,
  anon_sym_BSLASH_BSLASH = 35,
  sym_alnum = 36,
  aux_sym_identifier_token1 = 37,
  aux_sym_identifier_token2 = 38,
  sym_input = 39,
  sym_command = 40,
  sym__expression = 41,
  sym__esc_expression = 42,
  sym_variable = 43,
  sym_function = 44,
  sym_parameter = 45,
  sym_identifier = 46,
  aux_sym_input_repeat1 = 47,
  aux_sym__expression_repeat1 = 48,
  aux_sym__esc_expression_repeat1 = 49,
  aux_sym_function_repeat1 = 50,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SLASH] = "/",
  [anon_sym_announce] = "announce",
  [anon_sym_DOLLAR_LPAREN] = "$(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOT] = ".",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_BANG] = "!",
  [anon_sym_AT] = "@",
  [anon_sym_POUND] = "#",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_PERCENT] = "%",
  [anon_sym_CARET] = "^",
  [anon_sym_AMP] = "&",
  [anon_sym_STAR] = "*",
  [anon_sym_LPAREN] = "(",
  [anon_sym_DASH] = "-",
  [anon_sym__] = "_",
  [anon_sym_EQ] = "=",
  [anon_sym_PLUS] = "+",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_QMARK] = "\?",
  [anon_sym_COLON] = ":",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_BSLASH_LPAREN] = "\\(",
  [anon_sym_BSLASH_RPAREN] = "\\)",
  [anon_sym_BSLASH_BSLASH] = "\\\\",
  [sym_alnum] = "alnum",
  [aux_sym_identifier_token1] = "identifier_token1",
  [aux_sym_identifier_token2] = "identifier_token2",
  [sym_input] = "input",
  [sym_command] = "command",
  [sym__expression] = "_expression",
  [sym__esc_expression] = "_esc_expression",
  [sym_variable] = "variable",
  [sym_function] = "function",
  [sym_parameter] = "parameter",
  [sym_identifier] = "identifier",
  [aux_sym_input_repeat1] = "input_repeat1",
  [aux_sym__expression_repeat1] = "_expression_repeat1",
  [aux_sym__esc_expression_repeat1] = "_esc_expression_repeat1",
  [aux_sym_function_repeat1] = "function_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_announce] = anon_sym_announce,
  [anon_sym_DOLLAR_LPAREN] = anon_sym_DOLLAR_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym__] = anon_sym__,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_BSLASH_LPAREN] = anon_sym_BSLASH_LPAREN,
  [anon_sym_BSLASH_RPAREN] = anon_sym_BSLASH_RPAREN,
  [anon_sym_BSLASH_BSLASH] = anon_sym_BSLASH_BSLASH,
  [sym_alnum] = sym_alnum,
  [aux_sym_identifier_token1] = aux_sym_identifier_token1,
  [aux_sym_identifier_token2] = aux_sym_identifier_token2,
  [sym_input] = sym_input,
  [sym_command] = sym_command,
  [sym__expression] = sym__expression,
  [sym__esc_expression] = sym__esc_expression,
  [sym_variable] = sym_variable,
  [sym_function] = sym_function,
  [sym_parameter] = sym_parameter,
  [sym_identifier] = sym_identifier,
  [aux_sym_input_repeat1] = aux_sym_input_repeat1,
  [aux_sym__expression_repeat1] = aux_sym__expression_repeat1,
  [aux_sym__esc_expression_repeat1] = aux_sym__esc_expression_repeat1,
  [aux_sym_function_repeat1] = aux_sym_function_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_announce] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_alnum] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifier_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_input] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__esc_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_input_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__esc_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_parameters = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_parameters] = "parameters",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 1},
    {field_parameters, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 5,
  [6] = 5,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 35,
  [38] = 33,
  [39] = 36,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 42,
  [44] = 44,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '!', 20,
        '"', 12,
        '#', 22,
        '$', 23,
        '%', 24,
        '&', 26,
        '\'', 13,
        '(', 28,
        ')', 11,
        '*', 27,
        '+', 32,
        ',', 15,
        '-', 29,
        '.', 16,
        '/', 8,
        ':', 36,
        ';', 17,
        '<', 33,
        '=', 31,
        '>', 34,
        '?', 35,
        '@', 21,
        '[', 18,
        '\\', 38,
        ']', 19,
        '^', 25,
        '_', 30,
        '`', 14,
        'a', 48,
        '{', 39,
        '}', 40,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (('b' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(52);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 20,
        '"', 12,
        '#', 22,
        '$', 23,
        '%', 24,
        '&', 26,
        '\'', 13,
        '(', 28,
        ')', 11,
        '*', 27,
        '+', 32,
        ',', 15,
        '-', 29,
        '.', 16,
        '/', 8,
        ':', 36,
        ';', 17,
        '<', 33,
        '=', 31,
        '>', 34,
        '?', 35,
        '@', 21,
        '[', 18,
        '\\', 38,
        ']', 19,
        '^', 25,
        '_', 30,
        '`', 14,
        '{', 39,
        '}', 40,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(52);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '!', 20,
        '#', 22,
        '$', 23,
        '%', 24,
        '&', 26,
        '\'', 13,
        '(', 28,
        ')', 11,
        '*', 27,
        '+', 32,
        ',', 15,
        '-', 29,
        '.', 16,
        '/', 8,
        ':', 36,
        ';', 17,
        '<', 33,
        '=', 31,
        '>', 34,
        '?', 35,
        '@', 21,
        '[', 18,
        '\\', 37,
        ']', 19,
        '^', 25,
        '_', 30,
        'a', 48,
        '{', 39,
        '}', 40,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (('b' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(52);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '!', 20,
        '#', 22,
        '$', 23,
        '%', 24,
        '&', 26,
        '\'', 13,
        '(', 28,
        ')', 11,
        '*', 27,
        '+', 32,
        ',', 15,
        '-', 29,
        '.', 16,
        '/', 8,
        ':', 36,
        ';', 17,
        '<', 33,
        '=', 31,
        '>', 34,
        '?', 35,
        '@', 21,
        '[', 18,
        '\\', 37,
        ']', 19,
        '^', 25,
        '_', 30,
        '{', 39,
        '}', 40,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(52);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 4:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 5:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '!', 20,
        '"', 12,
        '#', 22,
        '$', 23,
        '%', 24,
        '&', 26,
        '\'', 13,
        '(', 28,
        ')', 11,
        '*', 27,
        '+', 32,
        ',', 15,
        '-', 29,
        '.', 16,
        '/', 8,
        ':', 36,
        ';', 17,
        '<', 33,
        '=', 31,
        '>', 34,
        '?', 35,
        '@', 21,
        '[', 18,
        '\\', 38,
        ']', 19,
        '^', 25,
        '_', 30,
        '`', 14,
        '{', 39,
        '}', 40,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(52);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '!', 20,
        '"', 12,
        '#', 22,
        '$', 23,
        '%', 24,
        '&', 26,
        '\'', 13,
        '(', 28,
        ')', 11,
        '*', 27,
        '+', 32,
        ',', 15,
        '-', 29,
        '.', 16,
        '/', 8,
        ':', 36,
        ';', 17,
        '<', 33,
        '=', 31,
        '>', 34,
        '?', 35,
        '@', 21,
        '[', 18,
        '\\', 37,
        ']', 19,
        '^', 25,
        '_', 30,
        '`', 14,
        '{', 39,
        '}', 40,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(52);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_announce);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(52);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (lookahead == '(') ADVANCE(10);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym__);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      if (lookahead == '(') ADVANCE(41);
      if (lookahead == ')') ADVANCE(42);
      if (lookahead == '\\') ADVANCE(43);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_BSLASH_LPAREN);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_BSLASH_RPAREN);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_BSLASH_BSLASH);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_alnum);
      if (lookahead == 'c') ADVANCE(45);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(52);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_alnum);
      if (lookahead == 'e') ADVANCE(9);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(52);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_alnum);
      if (lookahead == 'n') ADVANCE(49);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(52);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_alnum);
      if (lookahead == 'n') ADVANCE(44);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(52);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_alnum);
      if (lookahead == 'n') ADVANCE(46);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(52);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_alnum);
      if (lookahead == 'o') ADVANCE(50);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(52);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_alnum);
      if (lookahead == 'u') ADVANCE(47);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(52);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_alnum);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_alnum);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_identifier_token2);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 6},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 6},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 6},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_announce] = ACTIONS(1),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(1),
    [anon_sym_BSLASH_RPAREN] = ACTIONS(1),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(1),
    [sym_alnum] = ACTIONS(1),
    [aux_sym_identifier_token1] = ACTIONS(1),
    [aux_sym_identifier_token2] = ACTIONS(1),
  },
  [1] = {
    [sym_input] = STATE(44),
    [sym_command] = STATE(9),
    [sym__expression] = STATE(13),
    [sym_variable] = STATE(20),
    [sym_function] = STATE(20),
    [sym_identifier] = STATE(20),
    [aux_sym_input_repeat1] = STATE(13),
    [aux_sym__expression_repeat1] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_SLASH] = ACTIONS(5),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_alnum] = ACTIONS(13),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [2] = {
    [sym__esc_expression] = STATE(32),
    [sym_variable] = STATE(21),
    [sym_function] = STATE(21),
    [sym_parameter] = STATE(2),
    [sym_identifier] = STATE(21),
    [aux_sym__esc_expression_repeat1] = STATE(19),
    [aux_sym_function_repeat1] = STATE(2),
    [anon_sym_SLASH] = ACTIONS(17),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(20),
    [anon_sym_RPAREN] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [anon_sym_SQUOTE] = ACTIONS(28),
    [anon_sym_BQUOTE] = ACTIONS(31),
    [anon_sym_COMMA] = ACTIONS(17),
    [anon_sym_DOT] = ACTIONS(17),
    [anon_sym_SEMI] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_RBRACK] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(17),
    [anon_sym_AT] = ACTIONS(17),
    [anon_sym_POUND] = ACTIONS(17),
    [anon_sym_DOLLAR] = ACTIONS(34),
    [anon_sym_PERCENT] = ACTIONS(17),
    [anon_sym_CARET] = ACTIONS(17),
    [anon_sym_AMP] = ACTIONS(17),
    [anon_sym_STAR] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(34),
    [anon_sym__] = ACTIONS(34),
    [anon_sym_EQ] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(17),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_GT] = ACTIONS(17),
    [anon_sym_QMARK] = ACTIONS(17),
    [anon_sym_COLON] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(17),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(17),
    [anon_sym_BSLASH_RPAREN] = ACTIONS(17),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(17),
    [sym_alnum] = ACTIONS(37),
    [aux_sym_identifier_token1] = ACTIONS(40),
    [aux_sym_identifier_token2] = ACTIONS(40),
  },
  [3] = {
    [sym__esc_expression] = STATE(32),
    [sym_variable] = STATE(21),
    [sym_function] = STATE(21),
    [sym_parameter] = STATE(2),
    [sym_identifier] = STATE(21),
    [aux_sym__esc_expression_repeat1] = STATE(19),
    [aux_sym_function_repeat1] = STATE(2),
    [anon_sym_SLASH] = ACTIONS(43),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(45),
    [anon_sym_RPAREN] = ACTIONS(47),
    [anon_sym_DQUOTE] = ACTIONS(49),
    [anon_sym_SQUOTE] = ACTIONS(51),
    [anon_sym_BQUOTE] = ACTIONS(53),
    [anon_sym_COMMA] = ACTIONS(43),
    [anon_sym_DOT] = ACTIONS(43),
    [anon_sym_SEMI] = ACTIONS(43),
    [anon_sym_LBRACK] = ACTIONS(43),
    [anon_sym_RBRACK] = ACTIONS(43),
    [anon_sym_BANG] = ACTIONS(43),
    [anon_sym_AT] = ACTIONS(43),
    [anon_sym_POUND] = ACTIONS(43),
    [anon_sym_DOLLAR] = ACTIONS(55),
    [anon_sym_PERCENT] = ACTIONS(43),
    [anon_sym_CARET] = ACTIONS(43),
    [anon_sym_AMP] = ACTIONS(43),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_DASH] = ACTIONS(55),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_EQ] = ACTIONS(43),
    [anon_sym_PLUS] = ACTIONS(43),
    [anon_sym_LT] = ACTIONS(43),
    [anon_sym_GT] = ACTIONS(43),
    [anon_sym_QMARK] = ACTIONS(43),
    [anon_sym_COLON] = ACTIONS(43),
    [anon_sym_LBRACE] = ACTIONS(43),
    [anon_sym_RBRACE] = ACTIONS(43),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(43),
    [anon_sym_BSLASH_RPAREN] = ACTIONS(43),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(43),
    [sym_alnum] = ACTIONS(57),
    [aux_sym_identifier_token1] = ACTIONS(59),
    [aux_sym_identifier_token2] = ACTIONS(59),
  },
  [4] = {
    [sym__esc_expression] = STATE(32),
    [sym_variable] = STATE(21),
    [sym_function] = STATE(21),
    [sym_parameter] = STATE(2),
    [sym_identifier] = STATE(21),
    [aux_sym__esc_expression_repeat1] = STATE(19),
    [aux_sym_function_repeat1] = STATE(2),
    [anon_sym_SLASH] = ACTIONS(43),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(45),
    [anon_sym_RPAREN] = ACTIONS(61),
    [anon_sym_DQUOTE] = ACTIONS(49),
    [anon_sym_SQUOTE] = ACTIONS(51),
    [anon_sym_BQUOTE] = ACTIONS(53),
    [anon_sym_COMMA] = ACTIONS(43),
    [anon_sym_DOT] = ACTIONS(43),
    [anon_sym_SEMI] = ACTIONS(43),
    [anon_sym_LBRACK] = ACTIONS(43),
    [anon_sym_RBRACK] = ACTIONS(43),
    [anon_sym_BANG] = ACTIONS(43),
    [anon_sym_AT] = ACTIONS(43),
    [anon_sym_POUND] = ACTIONS(43),
    [anon_sym_DOLLAR] = ACTIONS(55),
    [anon_sym_PERCENT] = ACTIONS(43),
    [anon_sym_CARET] = ACTIONS(43),
    [anon_sym_AMP] = ACTIONS(43),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_DASH] = ACTIONS(55),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_EQ] = ACTIONS(43),
    [anon_sym_PLUS] = ACTIONS(43),
    [anon_sym_LT] = ACTIONS(43),
    [anon_sym_GT] = ACTIONS(43),
    [anon_sym_QMARK] = ACTIONS(43),
    [anon_sym_COLON] = ACTIONS(43),
    [anon_sym_LBRACE] = ACTIONS(43),
    [anon_sym_RBRACE] = ACTIONS(43),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(43),
    [anon_sym_BSLASH_RPAREN] = ACTIONS(43),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(43),
    [sym_alnum] = ACTIONS(57),
    [aux_sym_identifier_token1] = ACTIONS(59),
    [aux_sym_identifier_token2] = ACTIONS(59),
  },
  [5] = {
    [sym__esc_expression] = STATE(32),
    [sym_variable] = STATE(21),
    [sym_function] = STATE(21),
    [sym_parameter] = STATE(4),
    [sym_identifier] = STATE(21),
    [aux_sym__esc_expression_repeat1] = STATE(19),
    [aux_sym_function_repeat1] = STATE(4),
    [anon_sym_SLASH] = ACTIONS(43),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(45),
    [anon_sym_RPAREN] = ACTIONS(63),
    [anon_sym_DQUOTE] = ACTIONS(49),
    [anon_sym_SQUOTE] = ACTIONS(51),
    [anon_sym_BQUOTE] = ACTIONS(53),
    [anon_sym_COMMA] = ACTIONS(43),
    [anon_sym_DOT] = ACTIONS(43),
    [anon_sym_SEMI] = ACTIONS(43),
    [anon_sym_LBRACK] = ACTIONS(43),
    [anon_sym_RBRACK] = ACTIONS(43),
    [anon_sym_BANG] = ACTIONS(43),
    [anon_sym_AT] = ACTIONS(43),
    [anon_sym_POUND] = ACTIONS(43),
    [anon_sym_DOLLAR] = ACTIONS(55),
    [anon_sym_PERCENT] = ACTIONS(43),
    [anon_sym_CARET] = ACTIONS(43),
    [anon_sym_AMP] = ACTIONS(43),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_DASH] = ACTIONS(55),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_EQ] = ACTIONS(43),
    [anon_sym_PLUS] = ACTIONS(43),
    [anon_sym_LT] = ACTIONS(43),
    [anon_sym_GT] = ACTIONS(43),
    [anon_sym_QMARK] = ACTIONS(43),
    [anon_sym_COLON] = ACTIONS(43),
    [anon_sym_LBRACE] = ACTIONS(43),
    [anon_sym_RBRACE] = ACTIONS(43),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(43),
    [anon_sym_BSLASH_RPAREN] = ACTIONS(43),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(43),
    [sym_alnum] = ACTIONS(57),
    [aux_sym_identifier_token1] = ACTIONS(59),
    [aux_sym_identifier_token2] = ACTIONS(59),
  },
  [6] = {
    [sym__esc_expression] = STATE(32),
    [sym_variable] = STATE(21),
    [sym_function] = STATE(21),
    [sym_parameter] = STATE(3),
    [sym_identifier] = STATE(21),
    [aux_sym__esc_expression_repeat1] = STATE(19),
    [aux_sym_function_repeat1] = STATE(3),
    [anon_sym_SLASH] = ACTIONS(43),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(45),
    [anon_sym_RPAREN] = ACTIONS(65),
    [anon_sym_DQUOTE] = ACTIONS(49),
    [anon_sym_SQUOTE] = ACTIONS(51),
    [anon_sym_BQUOTE] = ACTIONS(53),
    [anon_sym_COMMA] = ACTIONS(43),
    [anon_sym_DOT] = ACTIONS(43),
    [anon_sym_SEMI] = ACTIONS(43),
    [anon_sym_LBRACK] = ACTIONS(43),
    [anon_sym_RBRACK] = ACTIONS(43),
    [anon_sym_BANG] = ACTIONS(43),
    [anon_sym_AT] = ACTIONS(43),
    [anon_sym_POUND] = ACTIONS(43),
    [anon_sym_DOLLAR] = ACTIONS(55),
    [anon_sym_PERCENT] = ACTIONS(43),
    [anon_sym_CARET] = ACTIONS(43),
    [anon_sym_AMP] = ACTIONS(43),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_DASH] = ACTIONS(55),
    [anon_sym__] = ACTIONS(55),
    [anon_sym_EQ] = ACTIONS(43),
    [anon_sym_PLUS] = ACTIONS(43),
    [anon_sym_LT] = ACTIONS(43),
    [anon_sym_GT] = ACTIONS(43),
    [anon_sym_QMARK] = ACTIONS(43),
    [anon_sym_COLON] = ACTIONS(43),
    [anon_sym_LBRACE] = ACTIONS(43),
    [anon_sym_RBRACE] = ACTIONS(43),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(43),
    [anon_sym_BSLASH_RPAREN] = ACTIONS(43),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(43),
    [sym_alnum] = ACTIONS(57),
    [aux_sym_identifier_token1] = ACTIONS(59),
    [aux_sym_identifier_token2] = ACTIONS(59),
  },
  [7] = {
    [sym__expression] = STATE(7),
    [sym_variable] = STATE(20),
    [sym_function] = STATE(20),
    [sym_identifier] = STATE(20),
    [aux_sym_input_repeat1] = STATE(7),
    [aux_sym__expression_repeat1] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(67),
    [anon_sym_SLASH] = ACTIONS(69),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(72),
    [anon_sym_RPAREN] = ACTIONS(69),
    [anon_sym_DQUOTE] = ACTIONS(67),
    [anon_sym_SQUOTE] = ACTIONS(69),
    [anon_sym_BQUOTE] = ACTIONS(67),
    [anon_sym_COMMA] = ACTIONS(69),
    [anon_sym_DOT] = ACTIONS(69),
    [anon_sym_SEMI] = ACTIONS(69),
    [anon_sym_LBRACK] = ACTIONS(69),
    [anon_sym_RBRACK] = ACTIONS(69),
    [anon_sym_BANG] = ACTIONS(69),
    [anon_sym_AT] = ACTIONS(69),
    [anon_sym_POUND] = ACTIONS(69),
    [anon_sym_DOLLAR] = ACTIONS(75),
    [anon_sym_PERCENT] = ACTIONS(69),
    [anon_sym_CARET] = ACTIONS(69),
    [anon_sym_AMP] = ACTIONS(69),
    [anon_sym_STAR] = ACTIONS(69),
    [anon_sym_LPAREN] = ACTIONS(69),
    [anon_sym_DASH] = ACTIONS(75),
    [anon_sym__] = ACTIONS(75),
    [anon_sym_EQ] = ACTIONS(69),
    [anon_sym_PLUS] = ACTIONS(69),
    [anon_sym_LT] = ACTIONS(69),
    [anon_sym_GT] = ACTIONS(69),
    [anon_sym_QMARK] = ACTIONS(69),
    [anon_sym_COLON] = ACTIONS(69),
    [anon_sym_BSLASH] = ACTIONS(69),
    [anon_sym_LBRACE] = ACTIONS(69),
    [anon_sym_RBRACE] = ACTIONS(69),
    [sym_alnum] = ACTIONS(78),
    [aux_sym_identifier_token1] = ACTIONS(81),
    [aux_sym_identifier_token2] = ACTIONS(81),
  },
  [8] = {
    [sym__expression] = STATE(16),
    [sym_variable] = STATE(20),
    [sym_function] = STATE(20),
    [sym_identifier] = STATE(20),
    [aux_sym_input_repeat1] = STATE(16),
    [aux_sym__expression_repeat1] = STATE(23),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(84),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(86),
    [anon_sym_BSLASH_RPAREN] = ACTIONS(86),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(86),
    [sym_alnum] = ACTIONS(13),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [9] = {
    [sym__expression] = STATE(11),
    [sym_variable] = STATE(20),
    [sym_function] = STATE(20),
    [sym_identifier] = STATE(20),
    [aux_sym_input_repeat1] = STATE(11),
    [aux_sym__expression_repeat1] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(88),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_alnum] = ACTIONS(13),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [10] = {
    [sym__expression] = STATE(14),
    [sym_variable] = STATE(20),
    [sym_function] = STATE(20),
    [sym_identifier] = STATE(20),
    [aux_sym_input_repeat1] = STATE(14),
    [aux_sym__expression_repeat1] = STATE(23),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(90),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_alnum] = ACTIONS(13),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [11] = {
    [sym__expression] = STATE(7),
    [sym_variable] = STATE(20),
    [sym_function] = STATE(20),
    [sym_identifier] = STATE(20),
    [aux_sym_input_repeat1] = STATE(7),
    [aux_sym__expression_repeat1] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(92),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_alnum] = ACTIONS(13),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [12] = {
    [sym__expression] = STATE(15),
    [sym_variable] = STATE(20),
    [sym_function] = STATE(20),
    [sym_identifier] = STATE(20),
    [aux_sym_input_repeat1] = STATE(15),
    [aux_sym__expression_repeat1] = STATE(23),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(90),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_alnum] = ACTIONS(13),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [13] = {
    [sym__expression] = STATE(7),
    [sym_variable] = STATE(20),
    [sym_function] = STATE(20),
    [sym_identifier] = STATE(20),
    [aux_sym_input_repeat1] = STATE(7),
    [aux_sym__expression_repeat1] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(88),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_alnum] = ACTIONS(13),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [14] = {
    [sym__expression] = STATE(7),
    [sym_variable] = STATE(20),
    [sym_function] = STATE(20),
    [sym_identifier] = STATE(20),
    [aux_sym_input_repeat1] = STATE(7),
    [aux_sym__expression_repeat1] = STATE(23),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(94),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_alnum] = ACTIONS(13),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [15] = {
    [sym__expression] = STATE(7),
    [sym_variable] = STATE(20),
    [sym_function] = STATE(20),
    [sym_identifier] = STATE(20),
    [aux_sym_input_repeat1] = STATE(7),
    [aux_sym__expression_repeat1] = STATE(23),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(94),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_alnum] = ACTIONS(13),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [16] = {
    [sym__expression] = STATE(7),
    [sym_variable] = STATE(20),
    [sym_function] = STATE(20),
    [sym_identifier] = STATE(20),
    [aux_sym_input_repeat1] = STATE(7),
    [aux_sym__expression_repeat1] = STATE(23),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(96),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_alnum] = ACTIONS(13),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [17] = {
    [anon_sym_SLASH] = ACTIONS(98),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(98),
    [anon_sym_RPAREN] = ACTIONS(98),
    [anon_sym_DQUOTE] = ACTIONS(98),
    [anon_sym_SQUOTE] = ACTIONS(98),
    [anon_sym_BQUOTE] = ACTIONS(98),
    [anon_sym_COMMA] = ACTIONS(98),
    [anon_sym_DOT] = ACTIONS(98),
    [anon_sym_SEMI] = ACTIONS(98),
    [anon_sym_LBRACK] = ACTIONS(98),
    [anon_sym_RBRACK] = ACTIONS(98),
    [anon_sym_BANG] = ACTIONS(98),
    [anon_sym_AT] = ACTIONS(98),
    [anon_sym_POUND] = ACTIONS(98),
    [anon_sym_DOLLAR] = ACTIONS(100),
    [anon_sym_PERCENT] = ACTIONS(98),
    [anon_sym_CARET] = ACTIONS(98),
    [anon_sym_AMP] = ACTIONS(98),
    [anon_sym_STAR] = ACTIONS(98),
    [anon_sym_LPAREN] = ACTIONS(102),
    [anon_sym_DASH] = ACTIONS(100),
    [anon_sym__] = ACTIONS(100),
    [anon_sym_EQ] = ACTIONS(98),
    [anon_sym_PLUS] = ACTIONS(98),
    [anon_sym_LT] = ACTIONS(98),
    [anon_sym_GT] = ACTIONS(98),
    [anon_sym_QMARK] = ACTIONS(98),
    [anon_sym_COLON] = ACTIONS(98),
    [anon_sym_BSLASH] = ACTIONS(104),
    [anon_sym_LBRACE] = ACTIONS(98),
    [anon_sym_RBRACE] = ACTIONS(98),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(98),
    [anon_sym_BSLASH_RPAREN] = ACTIONS(98),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(98),
    [sym_alnum] = ACTIONS(100),
    [aux_sym_identifier_token1] = ACTIONS(100),
    [aux_sym_identifier_token2] = ACTIONS(100),
  },
  [18] = {
    [anon_sym_SLASH] = ACTIONS(106),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(106),
    [anon_sym_RPAREN] = ACTIONS(106),
    [anon_sym_DQUOTE] = ACTIONS(106),
    [anon_sym_SQUOTE] = ACTIONS(106),
    [anon_sym_BQUOTE] = ACTIONS(106),
    [anon_sym_COMMA] = ACTIONS(106),
    [anon_sym_DOT] = ACTIONS(106),
    [anon_sym_SEMI] = ACTIONS(106),
    [anon_sym_LBRACK] = ACTIONS(106),
    [anon_sym_RBRACK] = ACTIONS(106),
    [anon_sym_BANG] = ACTIONS(106),
    [anon_sym_AT] = ACTIONS(106),
    [anon_sym_POUND] = ACTIONS(106),
    [anon_sym_DOLLAR] = ACTIONS(108),
    [anon_sym_PERCENT] = ACTIONS(106),
    [anon_sym_CARET] = ACTIONS(106),
    [anon_sym_AMP] = ACTIONS(106),
    [anon_sym_STAR] = ACTIONS(106),
    [anon_sym_LPAREN] = ACTIONS(102),
    [anon_sym_DASH] = ACTIONS(108),
    [anon_sym__] = ACTIONS(108),
    [anon_sym_EQ] = ACTIONS(106),
    [anon_sym_PLUS] = ACTIONS(106),
    [anon_sym_LT] = ACTIONS(106),
    [anon_sym_GT] = ACTIONS(106),
    [anon_sym_QMARK] = ACTIONS(106),
    [anon_sym_COLON] = ACTIONS(106),
    [anon_sym_BSLASH] = ACTIONS(104),
    [anon_sym_LBRACE] = ACTIONS(106),
    [anon_sym_RBRACE] = ACTIONS(106),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(106),
    [anon_sym_BSLASH_RPAREN] = ACTIONS(106),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(106),
    [sym_alnum] = ACTIONS(108),
    [aux_sym_identifier_token1] = ACTIONS(108),
    [aux_sym_identifier_token2] = ACTIONS(108),
  },
  [19] = {
    [sym_variable] = STATE(27),
    [sym_function] = STATE(27),
    [sym_identifier] = STATE(27),
    [aux_sym__esc_expression_repeat1] = STATE(28),
    [anon_sym_SLASH] = ACTIONS(110),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(45),
    [anon_sym_SQUOTE] = ACTIONS(110),
    [anon_sym_COMMA] = ACTIONS(110),
    [anon_sym_DOT] = ACTIONS(110),
    [anon_sym_SEMI] = ACTIONS(110),
    [anon_sym_LBRACK] = ACTIONS(110),
    [anon_sym_RBRACK] = ACTIONS(110),
    [anon_sym_BANG] = ACTIONS(110),
    [anon_sym_AT] = ACTIONS(110),
    [anon_sym_POUND] = ACTIONS(110),
    [anon_sym_DOLLAR] = ACTIONS(112),
    [anon_sym_PERCENT] = ACTIONS(110),
    [anon_sym_CARET] = ACTIONS(110),
    [anon_sym_AMP] = ACTIONS(110),
    [anon_sym_STAR] = ACTIONS(110),
    [anon_sym_DASH] = ACTIONS(112),
    [anon_sym__] = ACTIONS(112),
    [anon_sym_EQ] = ACTIONS(110),
    [anon_sym_PLUS] = ACTIONS(110),
    [anon_sym_LT] = ACTIONS(110),
    [anon_sym_GT] = ACTIONS(110),
    [anon_sym_QMARK] = ACTIONS(110),
    [anon_sym_COLON] = ACTIONS(110),
    [anon_sym_LBRACE] = ACTIONS(110),
    [anon_sym_RBRACE] = ACTIONS(110),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(110),
    [anon_sym_BSLASH_RPAREN] = ACTIONS(110),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(110),
    [sym_alnum] = ACTIONS(114),
    [aux_sym_identifier_token1] = ACTIONS(59),
    [aux_sym_identifier_token2] = ACTIONS(59),
  },
  [20] = {
    [aux_sym__expression_repeat1] = STATE(29),
    [ts_builtin_sym_end] = ACTIONS(116),
    [anon_sym_SLASH] = ACTIONS(118),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(116),
    [anon_sym_RPAREN] = ACTIONS(118),
    [anon_sym_DQUOTE] = ACTIONS(116),
    [anon_sym_SQUOTE] = ACTIONS(118),
    [anon_sym_BQUOTE] = ACTIONS(116),
    [anon_sym_COMMA] = ACTIONS(118),
    [anon_sym_DOT] = ACTIONS(118),
    [anon_sym_SEMI] = ACTIONS(118),
    [anon_sym_LBRACK] = ACTIONS(118),
    [anon_sym_RBRACK] = ACTIONS(118),
    [anon_sym_BANG] = ACTIONS(118),
    [anon_sym_AT] = ACTIONS(118),
    [anon_sym_POUND] = ACTIONS(118),
    [anon_sym_DOLLAR] = ACTIONS(120),
    [anon_sym_PERCENT] = ACTIONS(118),
    [anon_sym_CARET] = ACTIONS(118),
    [anon_sym_AMP] = ACTIONS(118),
    [anon_sym_STAR] = ACTIONS(118),
    [anon_sym_LPAREN] = ACTIONS(118),
    [anon_sym_DASH] = ACTIONS(120),
    [anon_sym__] = ACTIONS(120),
    [anon_sym_EQ] = ACTIONS(118),
    [anon_sym_PLUS] = ACTIONS(118),
    [anon_sym_LT] = ACTIONS(118),
    [anon_sym_GT] = ACTIONS(118),
    [anon_sym_QMARK] = ACTIONS(118),
    [anon_sym_COLON] = ACTIONS(118),
    [anon_sym_BSLASH] = ACTIONS(118),
    [anon_sym_LBRACE] = ACTIONS(118),
    [anon_sym_RBRACE] = ACTIONS(118),
    [sym_alnum] = ACTIONS(122),
    [aux_sym_identifier_token1] = ACTIONS(122),
    [aux_sym_identifier_token2] = ACTIONS(122),
  },
  [21] = {
    [aux_sym__esc_expression_repeat1] = STATE(26),
    [anon_sym_SLASH] = ACTIONS(124),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(126),
    [anon_sym_RPAREN] = ACTIONS(126),
    [anon_sym_DQUOTE] = ACTIONS(126),
    [anon_sym_SQUOTE] = ACTIONS(124),
    [anon_sym_BQUOTE] = ACTIONS(126),
    [anon_sym_COMMA] = ACTIONS(124),
    [anon_sym_DOT] = ACTIONS(124),
    [anon_sym_SEMI] = ACTIONS(124),
    [anon_sym_LBRACK] = ACTIONS(124),
    [anon_sym_RBRACK] = ACTIONS(124),
    [anon_sym_BANG] = ACTIONS(124),
    [anon_sym_AT] = ACTIONS(124),
    [anon_sym_POUND] = ACTIONS(124),
    [anon_sym_DOLLAR] = ACTIONS(128),
    [anon_sym_PERCENT] = ACTIONS(124),
    [anon_sym_CARET] = ACTIONS(124),
    [anon_sym_AMP] = ACTIONS(124),
    [anon_sym_STAR] = ACTIONS(124),
    [anon_sym_DASH] = ACTIONS(128),
    [anon_sym__] = ACTIONS(128),
    [anon_sym_EQ] = ACTIONS(124),
    [anon_sym_PLUS] = ACTIONS(124),
    [anon_sym_LT] = ACTIONS(124),
    [anon_sym_GT] = ACTIONS(124),
    [anon_sym_QMARK] = ACTIONS(124),
    [anon_sym_COLON] = ACTIONS(124),
    [anon_sym_LBRACE] = ACTIONS(124),
    [anon_sym_RBRACE] = ACTIONS(124),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(124),
    [anon_sym_BSLASH_RPAREN] = ACTIONS(124),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(124),
    [sym_alnum] = ACTIONS(130),
    [aux_sym_identifier_token1] = ACTIONS(130),
    [aux_sym_identifier_token2] = ACTIONS(130),
  },
  [22] = {
    [aux_sym__expression_repeat1] = STATE(25),
    [ts_builtin_sym_end] = ACTIONS(132),
    [anon_sym_SLASH] = ACTIONS(134),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(132),
    [anon_sym_RPAREN] = ACTIONS(134),
    [anon_sym_DQUOTE] = ACTIONS(132),
    [anon_sym_SQUOTE] = ACTIONS(134),
    [anon_sym_BQUOTE] = ACTIONS(132),
    [anon_sym_COMMA] = ACTIONS(134),
    [anon_sym_DOT] = ACTIONS(134),
    [anon_sym_SEMI] = ACTIONS(134),
    [anon_sym_LBRACK] = ACTIONS(134),
    [anon_sym_RBRACK] = ACTIONS(134),
    [anon_sym_BANG] = ACTIONS(134),
    [anon_sym_AT] = ACTIONS(134),
    [anon_sym_POUND] = ACTIONS(134),
    [anon_sym_DOLLAR] = ACTIONS(136),
    [anon_sym_PERCENT] = ACTIONS(134),
    [anon_sym_CARET] = ACTIONS(134),
    [anon_sym_AMP] = ACTIONS(134),
    [anon_sym_STAR] = ACTIONS(134),
    [anon_sym_LPAREN] = ACTIONS(134),
    [anon_sym_DASH] = ACTIONS(136),
    [anon_sym__] = ACTIONS(136),
    [anon_sym_EQ] = ACTIONS(134),
    [anon_sym_PLUS] = ACTIONS(134),
    [anon_sym_LT] = ACTIONS(134),
    [anon_sym_GT] = ACTIONS(134),
    [anon_sym_QMARK] = ACTIONS(134),
    [anon_sym_COLON] = ACTIONS(134),
    [anon_sym_BSLASH] = ACTIONS(134),
    [anon_sym_LBRACE] = ACTIONS(134),
    [anon_sym_RBRACE] = ACTIONS(134),
    [sym_alnum] = ACTIONS(138),
    [aux_sym_identifier_token1] = ACTIONS(138),
    [aux_sym_identifier_token2] = ACTIONS(138),
  },
  [23] = {
    [sym_variable] = STATE(24),
    [sym_function] = STATE(24),
    [sym_identifier] = STATE(24),
    [aux_sym__expression_repeat1] = STATE(25),
    [anon_sym_SLASH] = ACTIONS(134),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(134),
    [anon_sym_SQUOTE] = ACTIONS(134),
    [anon_sym_COMMA] = ACTIONS(134),
    [anon_sym_DOT] = ACTIONS(134),
    [anon_sym_SEMI] = ACTIONS(134),
    [anon_sym_LBRACK] = ACTIONS(134),
    [anon_sym_RBRACK] = ACTIONS(134),
    [anon_sym_BANG] = ACTIONS(134),
    [anon_sym_AT] = ACTIONS(134),
    [anon_sym_POUND] = ACTIONS(134),
    [anon_sym_DOLLAR] = ACTIONS(136),
    [anon_sym_PERCENT] = ACTIONS(134),
    [anon_sym_CARET] = ACTIONS(134),
    [anon_sym_AMP] = ACTIONS(134),
    [anon_sym_STAR] = ACTIONS(134),
    [anon_sym_LPAREN] = ACTIONS(134),
    [anon_sym_DASH] = ACTIONS(136),
    [anon_sym__] = ACTIONS(136),
    [anon_sym_EQ] = ACTIONS(134),
    [anon_sym_PLUS] = ACTIONS(134),
    [anon_sym_LT] = ACTIONS(134),
    [anon_sym_GT] = ACTIONS(134),
    [anon_sym_QMARK] = ACTIONS(134),
    [anon_sym_COLON] = ACTIONS(134),
    [anon_sym_BSLASH] = ACTIONS(134),
    [anon_sym_LBRACE] = ACTIONS(134),
    [anon_sym_RBRACE] = ACTIONS(134),
    [sym_alnum] = ACTIONS(140),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [24] = {
    [aux_sym__expression_repeat1] = STATE(22),
    [ts_builtin_sym_end] = ACTIONS(142),
    [anon_sym_SLASH] = ACTIONS(144),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(142),
    [anon_sym_RPAREN] = ACTIONS(144),
    [anon_sym_DQUOTE] = ACTIONS(142),
    [anon_sym_SQUOTE] = ACTIONS(144),
    [anon_sym_BQUOTE] = ACTIONS(142),
    [anon_sym_COMMA] = ACTIONS(144),
    [anon_sym_DOT] = ACTIONS(144),
    [anon_sym_SEMI] = ACTIONS(144),
    [anon_sym_LBRACK] = ACTIONS(144),
    [anon_sym_RBRACK] = ACTIONS(144),
    [anon_sym_BANG] = ACTIONS(144),
    [anon_sym_AT] = ACTIONS(144),
    [anon_sym_POUND] = ACTIONS(144),
    [anon_sym_DOLLAR] = ACTIONS(146),
    [anon_sym_PERCENT] = ACTIONS(144),
    [anon_sym_CARET] = ACTIONS(144),
    [anon_sym_AMP] = ACTIONS(144),
    [anon_sym_STAR] = ACTIONS(144),
    [anon_sym_LPAREN] = ACTIONS(144),
    [anon_sym_DASH] = ACTIONS(146),
    [anon_sym__] = ACTIONS(146),
    [anon_sym_EQ] = ACTIONS(144),
    [anon_sym_PLUS] = ACTIONS(144),
    [anon_sym_LT] = ACTIONS(144),
    [anon_sym_GT] = ACTIONS(144),
    [anon_sym_QMARK] = ACTIONS(144),
    [anon_sym_COLON] = ACTIONS(144),
    [anon_sym_BSLASH] = ACTIONS(144),
    [anon_sym_LBRACE] = ACTIONS(144),
    [anon_sym_RBRACE] = ACTIONS(144),
    [sym_alnum] = ACTIONS(148),
    [aux_sym_identifier_token1] = ACTIONS(148),
    [aux_sym_identifier_token2] = ACTIONS(148),
  },
  [25] = {
    [aux_sym__expression_repeat1] = STATE(25),
    [ts_builtin_sym_end] = ACTIONS(150),
    [anon_sym_SLASH] = ACTIONS(152),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(150),
    [anon_sym_RPAREN] = ACTIONS(152),
    [anon_sym_DQUOTE] = ACTIONS(150),
    [anon_sym_SQUOTE] = ACTIONS(152),
    [anon_sym_BQUOTE] = ACTIONS(150),
    [anon_sym_COMMA] = ACTIONS(152),
    [anon_sym_DOT] = ACTIONS(152),
    [anon_sym_SEMI] = ACTIONS(152),
    [anon_sym_LBRACK] = ACTIONS(152),
    [anon_sym_RBRACK] = ACTIONS(152),
    [anon_sym_BANG] = ACTIONS(152),
    [anon_sym_AT] = ACTIONS(152),
    [anon_sym_POUND] = ACTIONS(152),
    [anon_sym_DOLLAR] = ACTIONS(155),
    [anon_sym_PERCENT] = ACTIONS(152),
    [anon_sym_CARET] = ACTIONS(152),
    [anon_sym_AMP] = ACTIONS(152),
    [anon_sym_STAR] = ACTIONS(152),
    [anon_sym_LPAREN] = ACTIONS(152),
    [anon_sym_DASH] = ACTIONS(155),
    [anon_sym__] = ACTIONS(155),
    [anon_sym_EQ] = ACTIONS(152),
    [anon_sym_PLUS] = ACTIONS(152),
    [anon_sym_LT] = ACTIONS(152),
    [anon_sym_GT] = ACTIONS(152),
    [anon_sym_QMARK] = ACTIONS(152),
    [anon_sym_COLON] = ACTIONS(152),
    [anon_sym_BSLASH] = ACTIONS(152),
    [anon_sym_LBRACE] = ACTIONS(152),
    [anon_sym_RBRACE] = ACTIONS(152),
    [sym_alnum] = ACTIONS(158),
    [aux_sym_identifier_token1] = ACTIONS(158),
    [aux_sym_identifier_token2] = ACTIONS(158),
  },
  [26] = {
    [aux_sym__esc_expression_repeat1] = STATE(28),
    [anon_sym_SLASH] = ACTIONS(110),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(160),
    [anon_sym_RPAREN] = ACTIONS(160),
    [anon_sym_DQUOTE] = ACTIONS(160),
    [anon_sym_SQUOTE] = ACTIONS(110),
    [anon_sym_BQUOTE] = ACTIONS(160),
    [anon_sym_COMMA] = ACTIONS(110),
    [anon_sym_DOT] = ACTIONS(110),
    [anon_sym_SEMI] = ACTIONS(110),
    [anon_sym_LBRACK] = ACTIONS(110),
    [anon_sym_RBRACK] = ACTIONS(110),
    [anon_sym_BANG] = ACTIONS(110),
    [anon_sym_AT] = ACTIONS(110),
    [anon_sym_POUND] = ACTIONS(110),
    [anon_sym_DOLLAR] = ACTIONS(112),
    [anon_sym_PERCENT] = ACTIONS(110),
    [anon_sym_CARET] = ACTIONS(110),
    [anon_sym_AMP] = ACTIONS(110),
    [anon_sym_STAR] = ACTIONS(110),
    [anon_sym_DASH] = ACTIONS(112),
    [anon_sym__] = ACTIONS(112),
    [anon_sym_EQ] = ACTIONS(110),
    [anon_sym_PLUS] = ACTIONS(110),
    [anon_sym_LT] = ACTIONS(110),
    [anon_sym_GT] = ACTIONS(110),
    [anon_sym_QMARK] = ACTIONS(110),
    [anon_sym_COLON] = ACTIONS(110),
    [anon_sym_LBRACE] = ACTIONS(110),
    [anon_sym_RBRACE] = ACTIONS(110),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(110),
    [anon_sym_BSLASH_RPAREN] = ACTIONS(110),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(110),
    [sym_alnum] = ACTIONS(162),
    [aux_sym_identifier_token1] = ACTIONS(162),
    [aux_sym_identifier_token2] = ACTIONS(162),
  },
  [27] = {
    [aux_sym__esc_expression_repeat1] = STATE(30),
    [anon_sym_SLASH] = ACTIONS(164),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(160),
    [anon_sym_RPAREN] = ACTIONS(160),
    [anon_sym_DQUOTE] = ACTIONS(160),
    [anon_sym_SQUOTE] = ACTIONS(164),
    [anon_sym_BQUOTE] = ACTIONS(160),
    [anon_sym_COMMA] = ACTIONS(164),
    [anon_sym_DOT] = ACTIONS(164),
    [anon_sym_SEMI] = ACTIONS(164),
    [anon_sym_LBRACK] = ACTIONS(164),
    [anon_sym_RBRACK] = ACTIONS(164),
    [anon_sym_BANG] = ACTIONS(164),
    [anon_sym_AT] = ACTIONS(164),
    [anon_sym_POUND] = ACTIONS(164),
    [anon_sym_DOLLAR] = ACTIONS(166),
    [anon_sym_PERCENT] = ACTIONS(164),
    [anon_sym_CARET] = ACTIONS(164),
    [anon_sym_AMP] = ACTIONS(164),
    [anon_sym_STAR] = ACTIONS(164),
    [anon_sym_DASH] = ACTIONS(166),
    [anon_sym__] = ACTIONS(166),
    [anon_sym_EQ] = ACTIONS(164),
    [anon_sym_PLUS] = ACTIONS(164),
    [anon_sym_LT] = ACTIONS(164),
    [anon_sym_GT] = ACTIONS(164),
    [anon_sym_QMARK] = ACTIONS(164),
    [anon_sym_COLON] = ACTIONS(164),
    [anon_sym_LBRACE] = ACTIONS(164),
    [anon_sym_RBRACE] = ACTIONS(164),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(164),
    [anon_sym_BSLASH_RPAREN] = ACTIONS(164),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(164),
    [sym_alnum] = ACTIONS(162),
    [aux_sym_identifier_token1] = ACTIONS(162),
    [aux_sym_identifier_token2] = ACTIONS(162),
  },
  [28] = {
    [aux_sym__esc_expression_repeat1] = STATE(28),
    [anon_sym_SLASH] = ACTIONS(168),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(171),
    [anon_sym_RPAREN] = ACTIONS(171),
    [anon_sym_DQUOTE] = ACTIONS(171),
    [anon_sym_SQUOTE] = ACTIONS(168),
    [anon_sym_BQUOTE] = ACTIONS(171),
    [anon_sym_COMMA] = ACTIONS(168),
    [anon_sym_DOT] = ACTIONS(168),
    [anon_sym_SEMI] = ACTIONS(168),
    [anon_sym_LBRACK] = ACTIONS(168),
    [anon_sym_RBRACK] = ACTIONS(168),
    [anon_sym_BANG] = ACTIONS(168),
    [anon_sym_AT] = ACTIONS(168),
    [anon_sym_POUND] = ACTIONS(168),
    [anon_sym_DOLLAR] = ACTIONS(173),
    [anon_sym_PERCENT] = ACTIONS(168),
    [anon_sym_CARET] = ACTIONS(168),
    [anon_sym_AMP] = ACTIONS(168),
    [anon_sym_STAR] = ACTIONS(168),
    [anon_sym_DASH] = ACTIONS(173),
    [anon_sym__] = ACTIONS(173),
    [anon_sym_EQ] = ACTIONS(168),
    [anon_sym_PLUS] = ACTIONS(168),
    [anon_sym_LT] = ACTIONS(168),
    [anon_sym_GT] = ACTIONS(168),
    [anon_sym_QMARK] = ACTIONS(168),
    [anon_sym_COLON] = ACTIONS(168),
    [anon_sym_LBRACE] = ACTIONS(168),
    [anon_sym_RBRACE] = ACTIONS(168),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(168),
    [anon_sym_BSLASH_RPAREN] = ACTIONS(168),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(168),
    [sym_alnum] = ACTIONS(176),
    [aux_sym_identifier_token1] = ACTIONS(176),
    [aux_sym_identifier_token2] = ACTIONS(176),
  },
  [29] = {
    [aux_sym__expression_repeat1] = STATE(25),
    [ts_builtin_sym_end] = ACTIONS(142),
    [anon_sym_SLASH] = ACTIONS(134),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(142),
    [anon_sym_RPAREN] = ACTIONS(134),
    [anon_sym_DQUOTE] = ACTIONS(142),
    [anon_sym_SQUOTE] = ACTIONS(134),
    [anon_sym_BQUOTE] = ACTIONS(142),
    [anon_sym_COMMA] = ACTIONS(134),
    [anon_sym_DOT] = ACTIONS(134),
    [anon_sym_SEMI] = ACTIONS(134),
    [anon_sym_LBRACK] = ACTIONS(134),
    [anon_sym_RBRACK] = ACTIONS(134),
    [anon_sym_BANG] = ACTIONS(134),
    [anon_sym_AT] = ACTIONS(134),
    [anon_sym_POUND] = ACTIONS(134),
    [anon_sym_DOLLAR] = ACTIONS(136),
    [anon_sym_PERCENT] = ACTIONS(134),
    [anon_sym_CARET] = ACTIONS(134),
    [anon_sym_AMP] = ACTIONS(134),
    [anon_sym_STAR] = ACTIONS(134),
    [anon_sym_LPAREN] = ACTIONS(134),
    [anon_sym_DASH] = ACTIONS(136),
    [anon_sym__] = ACTIONS(136),
    [anon_sym_EQ] = ACTIONS(134),
    [anon_sym_PLUS] = ACTIONS(134),
    [anon_sym_LT] = ACTIONS(134),
    [anon_sym_GT] = ACTIONS(134),
    [anon_sym_QMARK] = ACTIONS(134),
    [anon_sym_COLON] = ACTIONS(134),
    [anon_sym_BSLASH] = ACTIONS(134),
    [anon_sym_LBRACE] = ACTIONS(134),
    [anon_sym_RBRACE] = ACTIONS(134),
    [sym_alnum] = ACTIONS(148),
    [aux_sym_identifier_token1] = ACTIONS(148),
    [aux_sym_identifier_token2] = ACTIONS(148),
  },
  [30] = {
    [aux_sym__esc_expression_repeat1] = STATE(28),
    [anon_sym_SLASH] = ACTIONS(110),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(178),
    [anon_sym_RPAREN] = ACTIONS(178),
    [anon_sym_DQUOTE] = ACTIONS(178),
    [anon_sym_SQUOTE] = ACTIONS(110),
    [anon_sym_BQUOTE] = ACTIONS(178),
    [anon_sym_COMMA] = ACTIONS(110),
    [anon_sym_DOT] = ACTIONS(110),
    [anon_sym_SEMI] = ACTIONS(110),
    [anon_sym_LBRACK] = ACTIONS(110),
    [anon_sym_RBRACK] = ACTIONS(110),
    [anon_sym_BANG] = ACTIONS(110),
    [anon_sym_AT] = ACTIONS(110),
    [anon_sym_POUND] = ACTIONS(110),
    [anon_sym_DOLLAR] = ACTIONS(112),
    [anon_sym_PERCENT] = ACTIONS(110),
    [anon_sym_CARET] = ACTIONS(110),
    [anon_sym_AMP] = ACTIONS(110),
    [anon_sym_STAR] = ACTIONS(110),
    [anon_sym_DASH] = ACTIONS(112),
    [anon_sym__] = ACTIONS(112),
    [anon_sym_EQ] = ACTIONS(110),
    [anon_sym_PLUS] = ACTIONS(110),
    [anon_sym_LT] = ACTIONS(110),
    [anon_sym_GT] = ACTIONS(110),
    [anon_sym_QMARK] = ACTIONS(110),
    [anon_sym_COLON] = ACTIONS(110),
    [anon_sym_LBRACE] = ACTIONS(110),
    [anon_sym_RBRACE] = ACTIONS(110),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(110),
    [anon_sym_BSLASH_RPAREN] = ACTIONS(110),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(110),
    [sym_alnum] = ACTIONS(180),
    [aux_sym_identifier_token1] = ACTIONS(180),
    [aux_sym_identifier_token2] = ACTIONS(180),
  },
  [31] = {
    [anon_sym_SLASH] = ACTIONS(98),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(98),
    [anon_sym_RPAREN] = ACTIONS(98),
    [anon_sym_DQUOTE] = ACTIONS(98),
    [anon_sym_SQUOTE] = ACTIONS(98),
    [anon_sym_BQUOTE] = ACTIONS(98),
    [anon_sym_COMMA] = ACTIONS(98),
    [anon_sym_DOT] = ACTIONS(98),
    [anon_sym_SEMI] = ACTIONS(98),
    [anon_sym_LBRACK] = ACTIONS(98),
    [anon_sym_RBRACK] = ACTIONS(98),
    [anon_sym_BANG] = ACTIONS(98),
    [anon_sym_AT] = ACTIONS(98),
    [anon_sym_POUND] = ACTIONS(98),
    [anon_sym_DOLLAR] = ACTIONS(100),
    [anon_sym_PERCENT] = ACTIONS(98),
    [anon_sym_CARET] = ACTIONS(98),
    [anon_sym_AMP] = ACTIONS(98),
    [anon_sym_STAR] = ACTIONS(98),
    [anon_sym_DASH] = ACTIONS(100),
    [anon_sym__] = ACTIONS(100),
    [anon_sym_EQ] = ACTIONS(98),
    [anon_sym_PLUS] = ACTIONS(98),
    [anon_sym_LT] = ACTIONS(98),
    [anon_sym_GT] = ACTIONS(98),
    [anon_sym_QMARK] = ACTIONS(98),
    [anon_sym_COLON] = ACTIONS(98),
    [anon_sym_LBRACE] = ACTIONS(98),
    [anon_sym_RBRACE] = ACTIONS(98),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(98),
    [anon_sym_BSLASH_RPAREN] = ACTIONS(98),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(98),
    [sym_alnum] = ACTIONS(100),
    [aux_sym_identifier_token1] = ACTIONS(100),
    [aux_sym_identifier_token2] = ACTIONS(100),
  },
  [32] = {
    [anon_sym_SLASH] = ACTIONS(182),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(182),
    [anon_sym_RPAREN] = ACTIONS(182),
    [anon_sym_DQUOTE] = ACTIONS(182),
    [anon_sym_SQUOTE] = ACTIONS(182),
    [anon_sym_BQUOTE] = ACTIONS(182),
    [anon_sym_COMMA] = ACTIONS(182),
    [anon_sym_DOT] = ACTIONS(182),
    [anon_sym_SEMI] = ACTIONS(182),
    [anon_sym_LBRACK] = ACTIONS(182),
    [anon_sym_RBRACK] = ACTIONS(182),
    [anon_sym_BANG] = ACTIONS(182),
    [anon_sym_AT] = ACTIONS(182),
    [anon_sym_POUND] = ACTIONS(182),
    [anon_sym_DOLLAR] = ACTIONS(184),
    [anon_sym_PERCENT] = ACTIONS(182),
    [anon_sym_CARET] = ACTIONS(182),
    [anon_sym_AMP] = ACTIONS(182),
    [anon_sym_STAR] = ACTIONS(182),
    [anon_sym_DASH] = ACTIONS(184),
    [anon_sym__] = ACTIONS(184),
    [anon_sym_EQ] = ACTIONS(182),
    [anon_sym_PLUS] = ACTIONS(182),
    [anon_sym_LT] = ACTIONS(182),
    [anon_sym_GT] = ACTIONS(182),
    [anon_sym_QMARK] = ACTIONS(182),
    [anon_sym_COLON] = ACTIONS(182),
    [anon_sym_LBRACE] = ACTIONS(182),
    [anon_sym_RBRACE] = ACTIONS(182),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(182),
    [anon_sym_BSLASH_RPAREN] = ACTIONS(182),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(182),
    [sym_alnum] = ACTIONS(184),
    [aux_sym_identifier_token1] = ACTIONS(184),
    [aux_sym_identifier_token2] = ACTIONS(184),
  },
  [33] = {
    [ts_builtin_sym_end] = ACTIONS(186),
    [anon_sym_SLASH] = ACTIONS(186),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(186),
    [anon_sym_RPAREN] = ACTIONS(186),
    [anon_sym_DQUOTE] = ACTIONS(186),
    [anon_sym_SQUOTE] = ACTIONS(186),
    [anon_sym_BQUOTE] = ACTIONS(186),
    [anon_sym_COMMA] = ACTIONS(186),
    [anon_sym_DOT] = ACTIONS(186),
    [anon_sym_SEMI] = ACTIONS(186),
    [anon_sym_LBRACK] = ACTIONS(186),
    [anon_sym_RBRACK] = ACTIONS(186),
    [anon_sym_BANG] = ACTIONS(186),
    [anon_sym_AT] = ACTIONS(186),
    [anon_sym_POUND] = ACTIONS(186),
    [anon_sym_DOLLAR] = ACTIONS(188),
    [anon_sym_PERCENT] = ACTIONS(186),
    [anon_sym_CARET] = ACTIONS(186),
    [anon_sym_AMP] = ACTIONS(186),
    [anon_sym_STAR] = ACTIONS(186),
    [anon_sym_LPAREN] = ACTIONS(186),
    [anon_sym_DASH] = ACTIONS(188),
    [anon_sym__] = ACTIONS(188),
    [anon_sym_EQ] = ACTIONS(186),
    [anon_sym_PLUS] = ACTIONS(186),
    [anon_sym_LT] = ACTIONS(186),
    [anon_sym_GT] = ACTIONS(186),
    [anon_sym_QMARK] = ACTIONS(186),
    [anon_sym_COLON] = ACTIONS(186),
    [anon_sym_BSLASH] = ACTIONS(186),
    [anon_sym_LBRACE] = ACTIONS(186),
    [anon_sym_RBRACE] = ACTIONS(186),
    [sym_alnum] = ACTIONS(188),
    [aux_sym_identifier_token1] = ACTIONS(188),
    [aux_sym_identifier_token2] = ACTIONS(188),
  },
  [34] = {
    [anon_sym_SLASH] = ACTIONS(106),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(106),
    [anon_sym_RPAREN] = ACTIONS(106),
    [anon_sym_DQUOTE] = ACTIONS(106),
    [anon_sym_SQUOTE] = ACTIONS(106),
    [anon_sym_BQUOTE] = ACTIONS(106),
    [anon_sym_COMMA] = ACTIONS(106),
    [anon_sym_DOT] = ACTIONS(106),
    [anon_sym_SEMI] = ACTIONS(106),
    [anon_sym_LBRACK] = ACTIONS(106),
    [anon_sym_RBRACK] = ACTIONS(106),
    [anon_sym_BANG] = ACTIONS(106),
    [anon_sym_AT] = ACTIONS(106),
    [anon_sym_POUND] = ACTIONS(106),
    [anon_sym_DOLLAR] = ACTIONS(108),
    [anon_sym_PERCENT] = ACTIONS(106),
    [anon_sym_CARET] = ACTIONS(106),
    [anon_sym_AMP] = ACTIONS(106),
    [anon_sym_STAR] = ACTIONS(106),
    [anon_sym_DASH] = ACTIONS(108),
    [anon_sym__] = ACTIONS(108),
    [anon_sym_EQ] = ACTIONS(106),
    [anon_sym_PLUS] = ACTIONS(106),
    [anon_sym_LT] = ACTIONS(106),
    [anon_sym_GT] = ACTIONS(106),
    [anon_sym_QMARK] = ACTIONS(106),
    [anon_sym_COLON] = ACTIONS(106),
    [anon_sym_LBRACE] = ACTIONS(106),
    [anon_sym_RBRACE] = ACTIONS(106),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(106),
    [anon_sym_BSLASH_RPAREN] = ACTIONS(106),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(106),
    [sym_alnum] = ACTIONS(108),
    [aux_sym_identifier_token1] = ACTIONS(108),
    [aux_sym_identifier_token2] = ACTIONS(108),
  },
  [35] = {
    [ts_builtin_sym_end] = ACTIONS(190),
    [anon_sym_SLASH] = ACTIONS(190),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(190),
    [anon_sym_RPAREN] = ACTIONS(190),
    [anon_sym_DQUOTE] = ACTIONS(190),
    [anon_sym_SQUOTE] = ACTIONS(190),
    [anon_sym_BQUOTE] = ACTIONS(190),
    [anon_sym_COMMA] = ACTIONS(190),
    [anon_sym_DOT] = ACTIONS(190),
    [anon_sym_SEMI] = ACTIONS(190),
    [anon_sym_LBRACK] = ACTIONS(190),
    [anon_sym_RBRACK] = ACTIONS(190),
    [anon_sym_BANG] = ACTIONS(190),
    [anon_sym_AT] = ACTIONS(190),
    [anon_sym_POUND] = ACTIONS(190),
    [anon_sym_DOLLAR] = ACTIONS(192),
    [anon_sym_PERCENT] = ACTIONS(190),
    [anon_sym_CARET] = ACTIONS(190),
    [anon_sym_AMP] = ACTIONS(190),
    [anon_sym_STAR] = ACTIONS(190),
    [anon_sym_LPAREN] = ACTIONS(190),
    [anon_sym_DASH] = ACTIONS(192),
    [anon_sym__] = ACTIONS(192),
    [anon_sym_EQ] = ACTIONS(190),
    [anon_sym_PLUS] = ACTIONS(190),
    [anon_sym_LT] = ACTIONS(190),
    [anon_sym_GT] = ACTIONS(190),
    [anon_sym_QMARK] = ACTIONS(190),
    [anon_sym_COLON] = ACTIONS(190),
    [anon_sym_BSLASH] = ACTIONS(190),
    [anon_sym_LBRACE] = ACTIONS(190),
    [anon_sym_RBRACE] = ACTIONS(190),
    [sym_alnum] = ACTIONS(192),
    [aux_sym_identifier_token1] = ACTIONS(192),
    [aux_sym_identifier_token2] = ACTIONS(192),
  },
  [36] = {
    [anon_sym_SLASH] = ACTIONS(194),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(194),
    [anon_sym_RPAREN] = ACTIONS(194),
    [anon_sym_DQUOTE] = ACTIONS(194),
    [anon_sym_SQUOTE] = ACTIONS(194),
    [anon_sym_BQUOTE] = ACTIONS(194),
    [anon_sym_COMMA] = ACTIONS(194),
    [anon_sym_DOT] = ACTIONS(194),
    [anon_sym_SEMI] = ACTIONS(194),
    [anon_sym_LBRACK] = ACTIONS(194),
    [anon_sym_RBRACK] = ACTIONS(194),
    [anon_sym_BANG] = ACTIONS(194),
    [anon_sym_AT] = ACTIONS(194),
    [anon_sym_POUND] = ACTIONS(194),
    [anon_sym_DOLLAR] = ACTIONS(196),
    [anon_sym_PERCENT] = ACTIONS(194),
    [anon_sym_CARET] = ACTIONS(194),
    [anon_sym_AMP] = ACTIONS(194),
    [anon_sym_STAR] = ACTIONS(194),
    [anon_sym_DASH] = ACTIONS(196),
    [anon_sym__] = ACTIONS(196),
    [anon_sym_EQ] = ACTIONS(194),
    [anon_sym_PLUS] = ACTIONS(194),
    [anon_sym_LT] = ACTIONS(194),
    [anon_sym_GT] = ACTIONS(194),
    [anon_sym_QMARK] = ACTIONS(194),
    [anon_sym_COLON] = ACTIONS(194),
    [anon_sym_LBRACE] = ACTIONS(194),
    [anon_sym_RBRACE] = ACTIONS(194),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(194),
    [anon_sym_BSLASH_RPAREN] = ACTIONS(194),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(194),
    [sym_alnum] = ACTIONS(196),
    [aux_sym_identifier_token1] = ACTIONS(196),
    [aux_sym_identifier_token2] = ACTIONS(196),
  },
  [37] = {
    [anon_sym_SLASH] = ACTIONS(190),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(190),
    [anon_sym_RPAREN] = ACTIONS(190),
    [anon_sym_DQUOTE] = ACTIONS(190),
    [anon_sym_SQUOTE] = ACTIONS(190),
    [anon_sym_BQUOTE] = ACTIONS(190),
    [anon_sym_COMMA] = ACTIONS(190),
    [anon_sym_DOT] = ACTIONS(190),
    [anon_sym_SEMI] = ACTIONS(190),
    [anon_sym_LBRACK] = ACTIONS(190),
    [anon_sym_RBRACK] = ACTIONS(190),
    [anon_sym_BANG] = ACTIONS(190),
    [anon_sym_AT] = ACTIONS(190),
    [anon_sym_POUND] = ACTIONS(190),
    [anon_sym_DOLLAR] = ACTIONS(192),
    [anon_sym_PERCENT] = ACTIONS(190),
    [anon_sym_CARET] = ACTIONS(190),
    [anon_sym_AMP] = ACTIONS(190),
    [anon_sym_STAR] = ACTIONS(190),
    [anon_sym_DASH] = ACTIONS(192),
    [anon_sym__] = ACTIONS(192),
    [anon_sym_EQ] = ACTIONS(190),
    [anon_sym_PLUS] = ACTIONS(190),
    [anon_sym_LT] = ACTIONS(190),
    [anon_sym_GT] = ACTIONS(190),
    [anon_sym_QMARK] = ACTIONS(190),
    [anon_sym_COLON] = ACTIONS(190),
    [anon_sym_LBRACE] = ACTIONS(190),
    [anon_sym_RBRACE] = ACTIONS(190),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(190),
    [anon_sym_BSLASH_RPAREN] = ACTIONS(190),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(190),
    [sym_alnum] = ACTIONS(192),
    [aux_sym_identifier_token1] = ACTIONS(192),
    [aux_sym_identifier_token2] = ACTIONS(192),
  },
  [38] = {
    [anon_sym_SLASH] = ACTIONS(186),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(186),
    [anon_sym_RPAREN] = ACTIONS(186),
    [anon_sym_DQUOTE] = ACTIONS(186),
    [anon_sym_SQUOTE] = ACTIONS(186),
    [anon_sym_BQUOTE] = ACTIONS(186),
    [anon_sym_COMMA] = ACTIONS(186),
    [anon_sym_DOT] = ACTIONS(186),
    [anon_sym_SEMI] = ACTIONS(186),
    [anon_sym_LBRACK] = ACTIONS(186),
    [anon_sym_RBRACK] = ACTIONS(186),
    [anon_sym_BANG] = ACTIONS(186),
    [anon_sym_AT] = ACTIONS(186),
    [anon_sym_POUND] = ACTIONS(186),
    [anon_sym_DOLLAR] = ACTIONS(188),
    [anon_sym_PERCENT] = ACTIONS(186),
    [anon_sym_CARET] = ACTIONS(186),
    [anon_sym_AMP] = ACTIONS(186),
    [anon_sym_STAR] = ACTIONS(186),
    [anon_sym_DASH] = ACTIONS(188),
    [anon_sym__] = ACTIONS(188),
    [anon_sym_EQ] = ACTIONS(186),
    [anon_sym_PLUS] = ACTIONS(186),
    [anon_sym_LT] = ACTIONS(186),
    [anon_sym_GT] = ACTIONS(186),
    [anon_sym_QMARK] = ACTIONS(186),
    [anon_sym_COLON] = ACTIONS(186),
    [anon_sym_LBRACE] = ACTIONS(186),
    [anon_sym_RBRACE] = ACTIONS(186),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(186),
    [anon_sym_BSLASH_RPAREN] = ACTIONS(186),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(186),
    [sym_alnum] = ACTIONS(188),
    [aux_sym_identifier_token1] = ACTIONS(188),
    [aux_sym_identifier_token2] = ACTIONS(188),
  },
  [39] = {
    [ts_builtin_sym_end] = ACTIONS(194),
    [anon_sym_SLASH] = ACTIONS(194),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(194),
    [anon_sym_RPAREN] = ACTIONS(194),
    [anon_sym_DQUOTE] = ACTIONS(194),
    [anon_sym_SQUOTE] = ACTIONS(194),
    [anon_sym_BQUOTE] = ACTIONS(194),
    [anon_sym_COMMA] = ACTIONS(194),
    [anon_sym_DOT] = ACTIONS(194),
    [anon_sym_SEMI] = ACTIONS(194),
    [anon_sym_LBRACK] = ACTIONS(194),
    [anon_sym_RBRACK] = ACTIONS(194),
    [anon_sym_BANG] = ACTIONS(194),
    [anon_sym_AT] = ACTIONS(194),
    [anon_sym_POUND] = ACTIONS(194),
    [anon_sym_DOLLAR] = ACTIONS(196),
    [anon_sym_PERCENT] = ACTIONS(194),
    [anon_sym_CARET] = ACTIONS(194),
    [anon_sym_AMP] = ACTIONS(194),
    [anon_sym_STAR] = ACTIONS(194),
    [anon_sym_LPAREN] = ACTIONS(194),
    [anon_sym_DASH] = ACTIONS(196),
    [anon_sym__] = ACTIONS(196),
    [anon_sym_EQ] = ACTIONS(194),
    [anon_sym_PLUS] = ACTIONS(194),
    [anon_sym_LT] = ACTIONS(194),
    [anon_sym_GT] = ACTIONS(194),
    [anon_sym_QMARK] = ACTIONS(194),
    [anon_sym_COLON] = ACTIONS(194),
    [anon_sym_BSLASH] = ACTIONS(194),
    [anon_sym_LBRACE] = ACTIONS(194),
    [anon_sym_RBRACE] = ACTIONS(194),
    [sym_alnum] = ACTIONS(196),
    [aux_sym_identifier_token1] = ACTIONS(196),
    [aux_sym_identifier_token2] = ACTIONS(196),
  },
  [40] = {
    [anon_sym_SLASH] = ACTIONS(102),
    [anon_sym_announce] = ACTIONS(198),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(102),
    [anon_sym_RPAREN] = ACTIONS(102),
    [anon_sym_SQUOTE] = ACTIONS(102),
    [anon_sym_COMMA] = ACTIONS(102),
    [anon_sym_DOT] = ACTIONS(102),
    [anon_sym_SEMI] = ACTIONS(102),
    [anon_sym_LBRACK] = ACTIONS(102),
    [anon_sym_RBRACK] = ACTIONS(102),
    [anon_sym_BANG] = ACTIONS(102),
    [anon_sym_AT] = ACTIONS(102),
    [anon_sym_POUND] = ACTIONS(102),
    [anon_sym_DOLLAR] = ACTIONS(104),
    [anon_sym_PERCENT] = ACTIONS(102),
    [anon_sym_CARET] = ACTIONS(102),
    [anon_sym_AMP] = ACTIONS(102),
    [anon_sym_STAR] = ACTIONS(102),
    [anon_sym_LPAREN] = ACTIONS(102),
    [anon_sym_DASH] = ACTIONS(104),
    [anon_sym__] = ACTIONS(104),
    [anon_sym_EQ] = ACTIONS(102),
    [anon_sym_PLUS] = ACTIONS(102),
    [anon_sym_LT] = ACTIONS(102),
    [anon_sym_GT] = ACTIONS(102),
    [anon_sym_QMARK] = ACTIONS(102),
    [anon_sym_COLON] = ACTIONS(102),
    [anon_sym_BSLASH] = ACTIONS(102),
    [anon_sym_LBRACE] = ACTIONS(102),
    [anon_sym_RBRACE] = ACTIONS(102),
    [sym_alnum] = ACTIONS(104),
    [aux_sym_identifier_token1] = ACTIONS(104),
    [aux_sym_identifier_token2] = ACTIONS(104),
  },
  [41] = {
    [ts_builtin_sym_end] = ACTIONS(200),
    [anon_sym_SLASH] = ACTIONS(200),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(200),
    [anon_sym_RPAREN] = ACTIONS(200),
    [anon_sym_SQUOTE] = ACTIONS(200),
    [anon_sym_COMMA] = ACTIONS(200),
    [anon_sym_DOT] = ACTIONS(200),
    [anon_sym_SEMI] = ACTIONS(200),
    [anon_sym_LBRACK] = ACTIONS(200),
    [anon_sym_RBRACK] = ACTIONS(200),
    [anon_sym_BANG] = ACTIONS(200),
    [anon_sym_AT] = ACTIONS(200),
    [anon_sym_POUND] = ACTIONS(200),
    [anon_sym_DOLLAR] = ACTIONS(202),
    [anon_sym_PERCENT] = ACTIONS(200),
    [anon_sym_CARET] = ACTIONS(200),
    [anon_sym_AMP] = ACTIONS(200),
    [anon_sym_STAR] = ACTIONS(200),
    [anon_sym_LPAREN] = ACTIONS(200),
    [anon_sym_DASH] = ACTIONS(202),
    [anon_sym__] = ACTIONS(202),
    [anon_sym_EQ] = ACTIONS(200),
    [anon_sym_PLUS] = ACTIONS(200),
    [anon_sym_LT] = ACTIONS(200),
    [anon_sym_GT] = ACTIONS(200),
    [anon_sym_QMARK] = ACTIONS(200),
    [anon_sym_COLON] = ACTIONS(200),
    [anon_sym_BSLASH] = ACTIONS(200),
    [anon_sym_LBRACE] = ACTIONS(200),
    [anon_sym_RBRACE] = ACTIONS(200),
    [sym_alnum] = ACTIONS(202),
    [aux_sym_identifier_token1] = ACTIONS(202),
    [aux_sym_identifier_token2] = ACTIONS(202),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    STATE(5), 1,
      sym_identifier,
    ACTIONS(204), 2,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
  [8] = 2,
    STATE(6), 1,
      sym_identifier,
    ACTIONS(204), 2,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
  [16] = 1,
    ACTIONS(206), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(42)] = 0,
  [SMALL_STATE(43)] = 8,
  [SMALL_STATE(44)] = 16,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [81] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__esc_expression_repeat1, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__expression_repeat1, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__expression_repeat1, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [120] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__esc_expression, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__esc_expression, 1, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__expression_repeat1, 2, 0, 0),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expression_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [155] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expression_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__expression_repeat1, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__esc_expression, 2, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__esc_expression, 2, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__esc_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__esc_expression_repeat1, 2, 0, 0),
  [173] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__esc_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__esc_expression_repeat1, 2, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__esc_expression, 3, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__esc_expression, 3, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 1, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 1, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, 0, 1),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 3, 0, 1),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 4, 0, 2),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 4, 0, 2),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 2, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [206] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_akbs(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
