#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 44
#define LARGE_STATE_COUNT 41
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 3

enum ts_symbol_identifiers {
  sym_command = 1,
  anon_sym_DOLLAR_LPAREN = 2,
  anon_sym_RPAREN = 3,
  anon_sym_DQUOTE = 4,
  anon_sym_SQUOTE = 5,
  anon_sym_BQUOTE = 6,
  anon_sym_COMMA = 7,
  anon_sym_DOT = 8,
  anon_sym_SLASH = 9,
  anon_sym_SEMI = 10,
  anon_sym_LBRACK = 11,
  anon_sym_RBRACK = 12,
  anon_sym_BANG = 13,
  anon_sym_AT = 14,
  anon_sym_POUND = 15,
  anon_sym_DOLLAR = 16,
  anon_sym_PERCENT = 17,
  anon_sym_CARET = 18,
  anon_sym_AMP = 19,
  anon_sym_STAR = 20,
  anon_sym_LPAREN = 21,
  anon_sym_DASH = 22,
  anon_sym__ = 23,
  anon_sym_EQ = 24,
  anon_sym_PLUS = 25,
  anon_sym_LT = 26,
  anon_sym_GT = 27,
  anon_sym_QMARK = 28,
  anon_sym_COLON = 29,
  anon_sym_BSLASH = 30,
  anon_sym_LBRACE = 31,
  anon_sym_RBRACE = 32,
  sym_alnum = 33,
  aux_sym_identifier_token1 = 34,
  aux_sym_identifier_token2 = 35,
  sym_input = 36,
  sym__expression = 37,
  sym_variable = 38,
  sym_function = 39,
  sym_parameter = 40,
  sym_identifier = 41,
  aux_sym_input_repeat1 = 42,
  aux_sym__expression_repeat1 = 43,
  aux_sym_function_repeat1 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_command] = "command",
  [anon_sym_DOLLAR_LPAREN] = "$(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOT] = ".",
  [anon_sym_SLASH] = "/",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_BANG] = "!",
  [anon_sym_AT] = "@",
  [anon_sym_POUND] = "#",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_PERCENT] = "%",
  [anon_sym_CARET] = "^",
  [anon_sym_AMP] = "&",
  [anon_sym_STAR] = "*",
  [anon_sym_LPAREN] = "(",
  [anon_sym_DASH] = "-",
  [anon_sym__] = "_",
  [anon_sym_EQ] = "=",
  [anon_sym_PLUS] = "+",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_QMARK] = "\?",
  [anon_sym_COLON] = ":",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_alnum] = "alnum",
  [aux_sym_identifier_token1] = "identifier_token1",
  [aux_sym_identifier_token2] = "identifier_token2",
  [sym_input] = "input",
  [sym__expression] = "_expression",
  [sym_variable] = "variable",
  [sym_function] = "function",
  [sym_parameter] = "parameter",
  [sym_identifier] = "identifier",
  [aux_sym_input_repeat1] = "input_repeat1",
  [aux_sym__expression_repeat1] = "_expression_repeat1",
  [aux_sym_function_repeat1] = "function_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_command] = sym_command,
  [anon_sym_DOLLAR_LPAREN] = anon_sym_DOLLAR_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym__] = anon_sym__,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_alnum] = sym_alnum,
  [aux_sym_identifier_token1] = aux_sym_identifier_token1,
  [aux_sym_identifier_token2] = aux_sym_identifier_token2,
  [sym_input] = sym_input,
  [sym__expression] = sym__expression,
  [sym_variable] = sym_variable,
  [sym_function] = sym_function,
  [sym_parameter] = sym_parameter,
  [sym_identifier] = sym_identifier,
  [aux_sym_input_repeat1] = aux_sym_input_repeat1,
  [aux_sym__expression_repeat1] = aux_sym__expression_repeat1,
  [aux_sym_function_repeat1] = aux_sym_function_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_alnum] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifier_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_input] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_input_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_parameters = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_parameters] = "parameters",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 1},
    {field_parameters, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 4,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 7,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 18,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 22,
  [27] = 27,
  [28] = 23,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 24,
  [33] = 33,
  [34] = 34,
  [35] = 20,
  [36] = 21,
  [37] = 37,
  [38] = 37,
  [39] = 25,
  [40] = 29,
  [41] = 41,
  [42] = 41,
  [43] = 43,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '!', 24,
        '"', 14,
        '#', 26,
        '$', 27,
        '%', 28,
        '&', 30,
        '\'', 15,
        '(', 32,
        ')', 13,
        '*', 31,
        '+', 36,
        ',', 17,
        '-', 33,
        '.', 18,
        '/', 20,
        ':', 40,
        ';', 21,
        '<', 37,
        '=', 35,
        '>', 38,
        '?', 39,
        '@', 25,
        '[', 22,
        '\\', 41,
        ']', 23,
        '^', 29,
        '_', 34,
        '`', 16,
        '{', 42,
        '}', 43,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(45);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 1:
      if (lookahead == 'c') ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 4:
      if (lookahead == 'n') ADVANCE(1);
      END_STATE();
    case 5:
      if (lookahead == 'n') ADVANCE(3);
      END_STATE();
    case 6:
      if (lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == 'u') ADVANCE(4);
      END_STATE();
    case 8:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '!', 24,
        '"', 14,
        '#', 26,
        '$', 27,
        '%', 28,
        '&', 30,
        '\'', 15,
        '(', 32,
        ')', 13,
        '*', 31,
        '+', 36,
        ',', 17,
        '-', 33,
        '.', 18,
        '/', 19,
        ':', 40,
        ';', 21,
        '<', 37,
        '=', 35,
        '>', 38,
        '?', 39,
        '@', 25,
        '[', 22,
        '\\', 41,
        ']', 23,
        '^', 29,
        '_', 34,
        '`', 16,
        '{', 42,
        '}', 43,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(45);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_command);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == 'a') ADVANCE(5);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (lookahead == '(') ADVANCE(12);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym__);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_alnum);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_alnum);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_identifier_token2);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 9},
  [3] = {.lex_state = 9},
  [4] = {.lex_state = 9},
  [5] = {.lex_state = 9},
  [6] = {.lex_state = 9},
  [7] = {.lex_state = 9},
  [8] = {.lex_state = 9},
  [9] = {.lex_state = 9},
  [10] = {.lex_state = 9},
  [11] = {.lex_state = 9},
  [12] = {.lex_state = 9},
  [13] = {.lex_state = 9},
  [14] = {.lex_state = 9},
  [15] = {.lex_state = 9},
  [16] = {.lex_state = 9},
  [17] = {.lex_state = 9},
  [18] = {.lex_state = 9},
  [19] = {.lex_state = 9},
  [20] = {.lex_state = 9},
  [21] = {.lex_state = 9},
  [22] = {.lex_state = 9},
  [23] = {.lex_state = 9},
  [24] = {.lex_state = 9},
  [25] = {.lex_state = 9},
  [26] = {.lex_state = 9},
  [27] = {.lex_state = 9},
  [28] = {.lex_state = 9},
  [29] = {.lex_state = 9},
  [30] = {.lex_state = 9},
  [31] = {.lex_state = 9},
  [32] = {.lex_state = 9},
  [33] = {.lex_state = 9},
  [34] = {.lex_state = 9},
  [35] = {.lex_state = 9},
  [36] = {.lex_state = 9},
  [37] = {.lex_state = 9},
  [38] = {.lex_state = 9},
  [39] = {.lex_state = 9},
  [40] = {.lex_state = 9},
  [41] = {.lex_state = 8},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_command] = ACTIONS(1),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_alnum] = ACTIONS(1),
    [aux_sym_identifier_token1] = ACTIONS(1),
    [aux_sym_identifier_token2] = ACTIONS(1),
  },
  [1] = {
    [sym_input] = STATE(43),
    [sym__expression] = STATE(8),
    [sym_variable] = STATE(26),
    [sym_function] = STATE(26),
    [sym_identifier] = STATE(26),
    [aux_sym_input_repeat1] = STATE(8),
    [aux_sym__expression_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_command] = ACTIONS(5),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_SLASH] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_alnum] = ACTIONS(13),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [2] = {
    [sym__expression] = STATE(31),
    [sym_variable] = STATE(22),
    [sym_function] = STATE(22),
    [sym_parameter] = STATE(5),
    [sym_identifier] = STATE(22),
    [aux_sym__expression_repeat1] = STATE(19),
    [aux_sym_function_repeat1] = STATE(5),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_SQUOTE] = ACTIONS(23),
    [anon_sym_BQUOTE] = ACTIONS(25),
    [anon_sym_COMMA] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_POUND] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(29),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym__] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_QMARK] = ACTIONS(27),
    [anon_sym_COLON] = ACTIONS(27),
    [anon_sym_BSLASH] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(27),
    [sym_alnum] = ACTIONS(31),
    [aux_sym_identifier_token1] = ACTIONS(33),
    [aux_sym_identifier_token2] = ACTIONS(33),
  },
  [3] = {
    [sym__expression] = STATE(31),
    [sym_variable] = STATE(22),
    [sym_function] = STATE(22),
    [sym_parameter] = STATE(5),
    [sym_identifier] = STATE(22),
    [aux_sym__expression_repeat1] = STATE(19),
    [aux_sym_function_repeat1] = STATE(5),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(35),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_SQUOTE] = ACTIONS(23),
    [anon_sym_BQUOTE] = ACTIONS(25),
    [anon_sym_COMMA] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_POUND] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(29),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym__] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_QMARK] = ACTIONS(27),
    [anon_sym_COLON] = ACTIONS(27),
    [anon_sym_BSLASH] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(27),
    [sym_alnum] = ACTIONS(31),
    [aux_sym_identifier_token1] = ACTIONS(33),
    [aux_sym_identifier_token2] = ACTIONS(33),
  },
  [4] = {
    [sym__expression] = STATE(31),
    [sym_variable] = STATE(22),
    [sym_function] = STATE(22),
    [sym_parameter] = STATE(2),
    [sym_identifier] = STATE(22),
    [aux_sym__expression_repeat1] = STATE(19),
    [aux_sym_function_repeat1] = STATE(2),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(37),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_SQUOTE] = ACTIONS(23),
    [anon_sym_BQUOTE] = ACTIONS(25),
    [anon_sym_COMMA] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_POUND] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(29),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym__] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_QMARK] = ACTIONS(27),
    [anon_sym_COLON] = ACTIONS(27),
    [anon_sym_BSLASH] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(27),
    [sym_alnum] = ACTIONS(31),
    [aux_sym_identifier_token1] = ACTIONS(33),
    [aux_sym_identifier_token2] = ACTIONS(33),
  },
  [5] = {
    [sym__expression] = STATE(31),
    [sym_variable] = STATE(22),
    [sym_function] = STATE(22),
    [sym_parameter] = STATE(5),
    [sym_identifier] = STATE(22),
    [aux_sym__expression_repeat1] = STATE(19),
    [aux_sym_function_repeat1] = STATE(5),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(39),
    [anon_sym_RPAREN] = ACTIONS(42),
    [anon_sym_DQUOTE] = ACTIONS(45),
    [anon_sym_SQUOTE] = ACTIONS(48),
    [anon_sym_BQUOTE] = ACTIONS(51),
    [anon_sym_COMMA] = ACTIONS(42),
    [anon_sym_DOT] = ACTIONS(42),
    [anon_sym_SLASH] = ACTIONS(42),
    [anon_sym_SEMI] = ACTIONS(42),
    [anon_sym_LBRACK] = ACTIONS(42),
    [anon_sym_RBRACK] = ACTIONS(42),
    [anon_sym_BANG] = ACTIONS(42),
    [anon_sym_AT] = ACTIONS(42),
    [anon_sym_POUND] = ACTIONS(42),
    [anon_sym_DOLLAR] = ACTIONS(54),
    [anon_sym_PERCENT] = ACTIONS(42),
    [anon_sym_CARET] = ACTIONS(42),
    [anon_sym_AMP] = ACTIONS(42),
    [anon_sym_STAR] = ACTIONS(42),
    [anon_sym_LPAREN] = ACTIONS(42),
    [anon_sym_DASH] = ACTIONS(54),
    [anon_sym__] = ACTIONS(54),
    [anon_sym_EQ] = ACTIONS(42),
    [anon_sym_PLUS] = ACTIONS(42),
    [anon_sym_LT] = ACTIONS(42),
    [anon_sym_GT] = ACTIONS(42),
    [anon_sym_QMARK] = ACTIONS(42),
    [anon_sym_COLON] = ACTIONS(42),
    [anon_sym_BSLASH] = ACTIONS(42),
    [anon_sym_LBRACE] = ACTIONS(42),
    [anon_sym_RBRACE] = ACTIONS(42),
    [sym_alnum] = ACTIONS(57),
    [aux_sym_identifier_token1] = ACTIONS(60),
    [aux_sym_identifier_token2] = ACTIONS(60),
  },
  [6] = {
    [sym__expression] = STATE(31),
    [sym_variable] = STATE(22),
    [sym_function] = STATE(22),
    [sym_parameter] = STATE(3),
    [sym_identifier] = STATE(22),
    [aux_sym__expression_repeat1] = STATE(19),
    [aux_sym_function_repeat1] = STATE(3),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(63),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_SQUOTE] = ACTIONS(23),
    [anon_sym_BQUOTE] = ACTIONS(25),
    [anon_sym_COMMA] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_POUND] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(29),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym__] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_QMARK] = ACTIONS(27),
    [anon_sym_COLON] = ACTIONS(27),
    [anon_sym_BSLASH] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(27),
    [sym_alnum] = ACTIONS(31),
    [aux_sym_identifier_token1] = ACTIONS(33),
    [aux_sym_identifier_token2] = ACTIONS(33),
  },
  [7] = {
    [sym__expression] = STATE(7),
    [sym_variable] = STATE(22),
    [sym_function] = STATE(22),
    [sym_identifier] = STATE(22),
    [aux_sym_input_repeat1] = STATE(7),
    [aux_sym__expression_repeat1] = STATE(19),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(65),
    [anon_sym_RPAREN] = ACTIONS(68),
    [anon_sym_DQUOTE] = ACTIONS(71),
    [anon_sym_SQUOTE] = ACTIONS(68),
    [anon_sym_BQUOTE] = ACTIONS(71),
    [anon_sym_COMMA] = ACTIONS(68),
    [anon_sym_DOT] = ACTIONS(68),
    [anon_sym_SLASH] = ACTIONS(68),
    [anon_sym_SEMI] = ACTIONS(68),
    [anon_sym_LBRACK] = ACTIONS(68),
    [anon_sym_RBRACK] = ACTIONS(68),
    [anon_sym_BANG] = ACTIONS(68),
    [anon_sym_AT] = ACTIONS(68),
    [anon_sym_POUND] = ACTIONS(68),
    [anon_sym_DOLLAR] = ACTIONS(73),
    [anon_sym_PERCENT] = ACTIONS(68),
    [anon_sym_CARET] = ACTIONS(68),
    [anon_sym_AMP] = ACTIONS(68),
    [anon_sym_STAR] = ACTIONS(68),
    [anon_sym_LPAREN] = ACTIONS(68),
    [anon_sym_DASH] = ACTIONS(73),
    [anon_sym__] = ACTIONS(73),
    [anon_sym_EQ] = ACTIONS(68),
    [anon_sym_PLUS] = ACTIONS(68),
    [anon_sym_LT] = ACTIONS(68),
    [anon_sym_GT] = ACTIONS(68),
    [anon_sym_QMARK] = ACTIONS(68),
    [anon_sym_COLON] = ACTIONS(68),
    [anon_sym_BSLASH] = ACTIONS(68),
    [anon_sym_LBRACE] = ACTIONS(68),
    [anon_sym_RBRACE] = ACTIONS(68),
    [sym_alnum] = ACTIONS(76),
    [aux_sym_identifier_token1] = ACTIONS(79),
    [aux_sym_identifier_token2] = ACTIONS(79),
  },
  [8] = {
    [sym__expression] = STATE(10),
    [sym_variable] = STATE(26),
    [sym_function] = STATE(26),
    [sym_identifier] = STATE(26),
    [aux_sym_input_repeat1] = STATE(10),
    [aux_sym__expression_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(82),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_alnum] = ACTIONS(13),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [9] = {
    [sym__expression] = STATE(10),
    [sym_variable] = STATE(26),
    [sym_function] = STATE(26),
    [sym_identifier] = STATE(26),
    [aux_sym_input_repeat1] = STATE(10),
    [aux_sym__expression_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(84),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_alnum] = ACTIONS(13),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [10] = {
    [sym__expression] = STATE(10),
    [sym_variable] = STATE(26),
    [sym_function] = STATE(26),
    [sym_identifier] = STATE(26),
    [aux_sym_input_repeat1] = STATE(10),
    [aux_sym__expression_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(71),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(86),
    [anon_sym_RPAREN] = ACTIONS(89),
    [anon_sym_SQUOTE] = ACTIONS(89),
    [anon_sym_COMMA] = ACTIONS(89),
    [anon_sym_DOT] = ACTIONS(89),
    [anon_sym_SLASH] = ACTIONS(89),
    [anon_sym_SEMI] = ACTIONS(89),
    [anon_sym_LBRACK] = ACTIONS(89),
    [anon_sym_RBRACK] = ACTIONS(89),
    [anon_sym_BANG] = ACTIONS(89),
    [anon_sym_AT] = ACTIONS(89),
    [anon_sym_POUND] = ACTIONS(89),
    [anon_sym_DOLLAR] = ACTIONS(92),
    [anon_sym_PERCENT] = ACTIONS(89),
    [anon_sym_CARET] = ACTIONS(89),
    [anon_sym_AMP] = ACTIONS(89),
    [anon_sym_STAR] = ACTIONS(89),
    [anon_sym_LPAREN] = ACTIONS(89),
    [anon_sym_DASH] = ACTIONS(92),
    [anon_sym__] = ACTIONS(92),
    [anon_sym_EQ] = ACTIONS(89),
    [anon_sym_PLUS] = ACTIONS(89),
    [anon_sym_LT] = ACTIONS(89),
    [anon_sym_GT] = ACTIONS(89),
    [anon_sym_QMARK] = ACTIONS(89),
    [anon_sym_COLON] = ACTIONS(89),
    [anon_sym_BSLASH] = ACTIONS(89),
    [anon_sym_LBRACE] = ACTIONS(89),
    [anon_sym_RBRACE] = ACTIONS(89),
    [sym_alnum] = ACTIONS(95),
    [aux_sym_identifier_token1] = ACTIONS(98),
    [aux_sym_identifier_token2] = ACTIONS(98),
  },
  [11] = {
    [sym__expression] = STATE(15),
    [sym_variable] = STATE(22),
    [sym_function] = STATE(22),
    [sym_identifier] = STATE(22),
    [aux_sym_input_repeat1] = STATE(15),
    [aux_sym__expression_repeat1] = STATE(19),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_DQUOTE] = ACTIONS(101),
    [anon_sym_SQUOTE] = ACTIONS(27),
    [anon_sym_COMMA] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_POUND] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(29),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym__] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_QMARK] = ACTIONS(27),
    [anon_sym_COLON] = ACTIONS(27),
    [anon_sym_BSLASH] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(27),
    [sym_alnum] = ACTIONS(31),
    [aux_sym_identifier_token1] = ACTIONS(33),
    [aux_sym_identifier_token2] = ACTIONS(33),
  },
  [12] = {
    [sym__expression] = STATE(14),
    [sym_variable] = STATE(22),
    [sym_function] = STATE(22),
    [sym_identifier] = STATE(22),
    [aux_sym_input_repeat1] = STATE(14),
    [aux_sym__expression_repeat1] = STATE(19),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_SQUOTE] = ACTIONS(27),
    [anon_sym_BQUOTE] = ACTIONS(101),
    [anon_sym_COMMA] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_POUND] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(29),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym__] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_QMARK] = ACTIONS(27),
    [anon_sym_COLON] = ACTIONS(27),
    [anon_sym_BSLASH] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(27),
    [sym_alnum] = ACTIONS(31),
    [aux_sym_identifier_token1] = ACTIONS(33),
    [aux_sym_identifier_token2] = ACTIONS(33),
  },
  [13] = {
    [sym__expression] = STATE(9),
    [sym_variable] = STATE(26),
    [sym_function] = STATE(26),
    [sym_identifier] = STATE(26),
    [aux_sym_input_repeat1] = STATE(9),
    [aux_sym__expression_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(82),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [sym_alnum] = ACTIONS(13),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [14] = {
    [sym__expression] = STATE(7),
    [sym_variable] = STATE(22),
    [sym_function] = STATE(22),
    [sym_identifier] = STATE(22),
    [aux_sym_input_repeat1] = STATE(7),
    [aux_sym__expression_repeat1] = STATE(19),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_SQUOTE] = ACTIONS(27),
    [anon_sym_BQUOTE] = ACTIONS(103),
    [anon_sym_COMMA] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_POUND] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(29),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym__] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_QMARK] = ACTIONS(27),
    [anon_sym_COLON] = ACTIONS(27),
    [anon_sym_BSLASH] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(27),
    [sym_alnum] = ACTIONS(31),
    [aux_sym_identifier_token1] = ACTIONS(33),
    [aux_sym_identifier_token2] = ACTIONS(33),
  },
  [15] = {
    [sym__expression] = STATE(7),
    [sym_variable] = STATE(22),
    [sym_function] = STATE(22),
    [sym_identifier] = STATE(22),
    [aux_sym_input_repeat1] = STATE(7),
    [aux_sym__expression_repeat1] = STATE(19),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_DQUOTE] = ACTIONS(103),
    [anon_sym_SQUOTE] = ACTIONS(27),
    [anon_sym_COMMA] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_POUND] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(29),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym__] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_QMARK] = ACTIONS(27),
    [anon_sym_COLON] = ACTIONS(27),
    [anon_sym_BSLASH] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(27),
    [sym_alnum] = ACTIONS(31),
    [aux_sym_identifier_token1] = ACTIONS(33),
    [aux_sym_identifier_token2] = ACTIONS(33),
  },
  [16] = {
    [sym__expression] = STATE(17),
    [sym_variable] = STATE(22),
    [sym_function] = STATE(22),
    [sym_identifier] = STATE(22),
    [aux_sym_input_repeat1] = STATE(17),
    [aux_sym__expression_repeat1] = STATE(19),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_SQUOTE] = ACTIONS(105),
    [anon_sym_COMMA] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_POUND] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(29),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym__] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_QMARK] = ACTIONS(27),
    [anon_sym_COLON] = ACTIONS(27),
    [anon_sym_BSLASH] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(27),
    [sym_alnum] = ACTIONS(31),
    [aux_sym_identifier_token1] = ACTIONS(33),
    [aux_sym_identifier_token2] = ACTIONS(33),
  },
  [17] = {
    [sym__expression] = STATE(7),
    [sym_variable] = STATE(22),
    [sym_function] = STATE(22),
    [sym_identifier] = STATE(22),
    [aux_sym_input_repeat1] = STATE(7),
    [aux_sym__expression_repeat1] = STATE(19),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_SQUOTE] = ACTIONS(107),
    [anon_sym_COMMA] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_AT] = ACTIONS(27),
    [anon_sym_POUND] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(29),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_CARET] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym__] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_QMARK] = ACTIONS(27),
    [anon_sym_COLON] = ACTIONS(27),
    [anon_sym_BSLASH] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(27),
    [sym_alnum] = ACTIONS(31),
    [aux_sym_identifier_token1] = ACTIONS(33),
    [aux_sym_identifier_token2] = ACTIONS(33),
  },
  [18] = {
    [sym_variable] = STATE(28),
    [sym_function] = STATE(28),
    [sym_identifier] = STATE(28),
    [aux_sym__expression_repeat1] = STATE(20),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(109),
    [anon_sym_SQUOTE] = ACTIONS(109),
    [anon_sym_COMMA] = ACTIONS(109),
    [anon_sym_DOT] = ACTIONS(109),
    [anon_sym_SLASH] = ACTIONS(109),
    [anon_sym_SEMI] = ACTIONS(109),
    [anon_sym_LBRACK] = ACTIONS(109),
    [anon_sym_RBRACK] = ACTIONS(109),
    [anon_sym_BANG] = ACTIONS(109),
    [anon_sym_AT] = ACTIONS(109),
    [anon_sym_POUND] = ACTIONS(109),
    [anon_sym_DOLLAR] = ACTIONS(111),
    [anon_sym_PERCENT] = ACTIONS(109),
    [anon_sym_CARET] = ACTIONS(109),
    [anon_sym_AMP] = ACTIONS(109),
    [anon_sym_STAR] = ACTIONS(109),
    [anon_sym_LPAREN] = ACTIONS(109),
    [anon_sym_DASH] = ACTIONS(111),
    [anon_sym__] = ACTIONS(111),
    [anon_sym_EQ] = ACTIONS(109),
    [anon_sym_PLUS] = ACTIONS(109),
    [anon_sym_LT] = ACTIONS(109),
    [anon_sym_GT] = ACTIONS(109),
    [anon_sym_QMARK] = ACTIONS(109),
    [anon_sym_COLON] = ACTIONS(109),
    [anon_sym_BSLASH] = ACTIONS(109),
    [anon_sym_LBRACE] = ACTIONS(109),
    [anon_sym_RBRACE] = ACTIONS(109),
    [sym_alnum] = ACTIONS(113),
    [aux_sym_identifier_token1] = ACTIONS(15),
    [aux_sym_identifier_token2] = ACTIONS(15),
  },
  [19] = {
    [sym_variable] = STATE(23),
    [sym_function] = STATE(23),
    [sym_identifier] = STATE(23),
    [aux_sym__expression_repeat1] = STATE(20),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(109),
    [anon_sym_SQUOTE] = ACTIONS(109),
    [anon_sym_COMMA] = ACTIONS(109),
    [anon_sym_DOT] = ACTIONS(109),
    [anon_sym_SLASH] = ACTIONS(109),
    [anon_sym_SEMI] = ACTIONS(109),
    [anon_sym_LBRACK] = ACTIONS(109),
    [anon_sym_RBRACK] = ACTIONS(109),
    [anon_sym_BANG] = ACTIONS(109),
    [anon_sym_AT] = ACTIONS(109),
    [anon_sym_POUND] = ACTIONS(109),
    [anon_sym_DOLLAR] = ACTIONS(111),
    [anon_sym_PERCENT] = ACTIONS(109),
    [anon_sym_CARET] = ACTIONS(109),
    [anon_sym_AMP] = ACTIONS(109),
    [anon_sym_STAR] = ACTIONS(109),
    [anon_sym_LPAREN] = ACTIONS(109),
    [anon_sym_DASH] = ACTIONS(111),
    [anon_sym__] = ACTIONS(111),
    [anon_sym_EQ] = ACTIONS(109),
    [anon_sym_PLUS] = ACTIONS(109),
    [anon_sym_LT] = ACTIONS(109),
    [anon_sym_GT] = ACTIONS(109),
    [anon_sym_QMARK] = ACTIONS(109),
    [anon_sym_COLON] = ACTIONS(109),
    [anon_sym_BSLASH] = ACTIONS(109),
    [anon_sym_LBRACE] = ACTIONS(109),
    [anon_sym_RBRACE] = ACTIONS(109),
    [sym_alnum] = ACTIONS(115),
    [aux_sym_identifier_token1] = ACTIONS(33),
    [aux_sym_identifier_token2] = ACTIONS(33),
  },
  [20] = {
    [aux_sym__expression_repeat1] = STATE(20),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(117),
    [anon_sym_RPAREN] = ACTIONS(119),
    [anon_sym_DQUOTE] = ACTIONS(117),
    [anon_sym_SQUOTE] = ACTIONS(119),
    [anon_sym_BQUOTE] = ACTIONS(117),
    [anon_sym_COMMA] = ACTIONS(119),
    [anon_sym_DOT] = ACTIONS(119),
    [anon_sym_SLASH] = ACTIONS(119),
    [anon_sym_SEMI] = ACTIONS(119),
    [anon_sym_LBRACK] = ACTIONS(119),
    [anon_sym_RBRACK] = ACTIONS(119),
    [anon_sym_BANG] = ACTIONS(119),
    [anon_sym_AT] = ACTIONS(119),
    [anon_sym_POUND] = ACTIONS(119),
    [anon_sym_DOLLAR] = ACTIONS(122),
    [anon_sym_PERCENT] = ACTIONS(119),
    [anon_sym_CARET] = ACTIONS(119),
    [anon_sym_AMP] = ACTIONS(119),
    [anon_sym_STAR] = ACTIONS(119),
    [anon_sym_LPAREN] = ACTIONS(119),
    [anon_sym_DASH] = ACTIONS(122),
    [anon_sym__] = ACTIONS(122),
    [anon_sym_EQ] = ACTIONS(119),
    [anon_sym_PLUS] = ACTIONS(119),
    [anon_sym_LT] = ACTIONS(119),
    [anon_sym_GT] = ACTIONS(119),
    [anon_sym_QMARK] = ACTIONS(119),
    [anon_sym_COLON] = ACTIONS(119),
    [anon_sym_BSLASH] = ACTIONS(119),
    [anon_sym_LBRACE] = ACTIONS(119),
    [anon_sym_RBRACE] = ACTIONS(119),
    [sym_alnum] = ACTIONS(125),
    [aux_sym_identifier_token1] = ACTIONS(125),
    [aux_sym_identifier_token2] = ACTIONS(125),
  },
  [21] = {
    [aux_sym__expression_repeat1] = STATE(20),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(127),
    [anon_sym_RPAREN] = ACTIONS(109),
    [anon_sym_DQUOTE] = ACTIONS(127),
    [anon_sym_SQUOTE] = ACTIONS(109),
    [anon_sym_BQUOTE] = ACTIONS(127),
    [anon_sym_COMMA] = ACTIONS(109),
    [anon_sym_DOT] = ACTIONS(109),
    [anon_sym_SLASH] = ACTIONS(109),
    [anon_sym_SEMI] = ACTIONS(109),
    [anon_sym_LBRACK] = ACTIONS(109),
    [anon_sym_RBRACK] = ACTIONS(109),
    [anon_sym_BANG] = ACTIONS(109),
    [anon_sym_AT] = ACTIONS(109),
    [anon_sym_POUND] = ACTIONS(109),
    [anon_sym_DOLLAR] = ACTIONS(111),
    [anon_sym_PERCENT] = ACTIONS(109),
    [anon_sym_CARET] = ACTIONS(109),
    [anon_sym_AMP] = ACTIONS(109),
    [anon_sym_STAR] = ACTIONS(109),
    [anon_sym_LPAREN] = ACTIONS(109),
    [anon_sym_DASH] = ACTIONS(111),
    [anon_sym__] = ACTIONS(111),
    [anon_sym_EQ] = ACTIONS(109),
    [anon_sym_PLUS] = ACTIONS(109),
    [anon_sym_LT] = ACTIONS(109),
    [anon_sym_GT] = ACTIONS(109),
    [anon_sym_QMARK] = ACTIONS(109),
    [anon_sym_COLON] = ACTIONS(109),
    [anon_sym_BSLASH] = ACTIONS(109),
    [anon_sym_LBRACE] = ACTIONS(109),
    [anon_sym_RBRACE] = ACTIONS(109),
    [sym_alnum] = ACTIONS(129),
    [aux_sym_identifier_token1] = ACTIONS(129),
    [aux_sym_identifier_token2] = ACTIONS(129),
  },
  [22] = {
    [aux_sym__expression_repeat1] = STATE(21),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(131),
    [anon_sym_RPAREN] = ACTIONS(133),
    [anon_sym_DQUOTE] = ACTIONS(131),
    [anon_sym_SQUOTE] = ACTIONS(133),
    [anon_sym_BQUOTE] = ACTIONS(131),
    [anon_sym_COMMA] = ACTIONS(133),
    [anon_sym_DOT] = ACTIONS(133),
    [anon_sym_SLASH] = ACTIONS(133),
    [anon_sym_SEMI] = ACTIONS(133),
    [anon_sym_LBRACK] = ACTIONS(133),
    [anon_sym_RBRACK] = ACTIONS(133),
    [anon_sym_BANG] = ACTIONS(133),
    [anon_sym_AT] = ACTIONS(133),
    [anon_sym_POUND] = ACTIONS(133),
    [anon_sym_DOLLAR] = ACTIONS(135),
    [anon_sym_PERCENT] = ACTIONS(133),
    [anon_sym_CARET] = ACTIONS(133),
    [anon_sym_AMP] = ACTIONS(133),
    [anon_sym_STAR] = ACTIONS(133),
    [anon_sym_LPAREN] = ACTIONS(133),
    [anon_sym_DASH] = ACTIONS(135),
    [anon_sym__] = ACTIONS(135),
    [anon_sym_EQ] = ACTIONS(133),
    [anon_sym_PLUS] = ACTIONS(133),
    [anon_sym_LT] = ACTIONS(133),
    [anon_sym_GT] = ACTIONS(133),
    [anon_sym_QMARK] = ACTIONS(133),
    [anon_sym_COLON] = ACTIONS(133),
    [anon_sym_BSLASH] = ACTIONS(133),
    [anon_sym_LBRACE] = ACTIONS(133),
    [anon_sym_RBRACE] = ACTIONS(133),
    [sym_alnum] = ACTIONS(137),
    [aux_sym_identifier_token1] = ACTIONS(137),
    [aux_sym_identifier_token2] = ACTIONS(137),
  },
  [23] = {
    [aux_sym__expression_repeat1] = STATE(24),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(127),
    [anon_sym_RPAREN] = ACTIONS(139),
    [anon_sym_DQUOTE] = ACTIONS(127),
    [anon_sym_SQUOTE] = ACTIONS(139),
    [anon_sym_BQUOTE] = ACTIONS(127),
    [anon_sym_COMMA] = ACTIONS(139),
    [anon_sym_DOT] = ACTIONS(139),
    [anon_sym_SLASH] = ACTIONS(139),
    [anon_sym_SEMI] = ACTIONS(139),
    [anon_sym_LBRACK] = ACTIONS(139),
    [anon_sym_RBRACK] = ACTIONS(139),
    [anon_sym_BANG] = ACTIONS(139),
    [anon_sym_AT] = ACTIONS(139),
    [anon_sym_POUND] = ACTIONS(139),
    [anon_sym_DOLLAR] = ACTIONS(141),
    [anon_sym_PERCENT] = ACTIONS(139),
    [anon_sym_CARET] = ACTIONS(139),
    [anon_sym_AMP] = ACTIONS(139),
    [anon_sym_STAR] = ACTIONS(139),
    [anon_sym_LPAREN] = ACTIONS(139),
    [anon_sym_DASH] = ACTIONS(141),
    [anon_sym__] = ACTIONS(141),
    [anon_sym_EQ] = ACTIONS(139),
    [anon_sym_PLUS] = ACTIONS(139),
    [anon_sym_LT] = ACTIONS(139),
    [anon_sym_GT] = ACTIONS(139),
    [anon_sym_QMARK] = ACTIONS(139),
    [anon_sym_COLON] = ACTIONS(139),
    [anon_sym_BSLASH] = ACTIONS(139),
    [anon_sym_LBRACE] = ACTIONS(139),
    [anon_sym_RBRACE] = ACTIONS(139),
    [sym_alnum] = ACTIONS(129),
    [aux_sym_identifier_token1] = ACTIONS(129),
    [aux_sym_identifier_token2] = ACTIONS(129),
  },
  [24] = {
    [aux_sym__expression_repeat1] = STATE(20),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(143),
    [anon_sym_RPAREN] = ACTIONS(109),
    [anon_sym_DQUOTE] = ACTIONS(143),
    [anon_sym_SQUOTE] = ACTIONS(109),
    [anon_sym_BQUOTE] = ACTIONS(143),
    [anon_sym_COMMA] = ACTIONS(109),
    [anon_sym_DOT] = ACTIONS(109),
    [anon_sym_SLASH] = ACTIONS(109),
    [anon_sym_SEMI] = ACTIONS(109),
    [anon_sym_LBRACK] = ACTIONS(109),
    [anon_sym_RBRACK] = ACTIONS(109),
    [anon_sym_BANG] = ACTIONS(109),
    [anon_sym_AT] = ACTIONS(109),
    [anon_sym_POUND] = ACTIONS(109),
    [anon_sym_DOLLAR] = ACTIONS(111),
    [anon_sym_PERCENT] = ACTIONS(109),
    [anon_sym_CARET] = ACTIONS(109),
    [anon_sym_AMP] = ACTIONS(109),
    [anon_sym_STAR] = ACTIONS(109),
    [anon_sym_LPAREN] = ACTIONS(109),
    [anon_sym_DASH] = ACTIONS(111),
    [anon_sym__] = ACTIONS(111),
    [anon_sym_EQ] = ACTIONS(109),
    [anon_sym_PLUS] = ACTIONS(109),
    [anon_sym_LT] = ACTIONS(109),
    [anon_sym_GT] = ACTIONS(109),
    [anon_sym_QMARK] = ACTIONS(109),
    [anon_sym_COLON] = ACTIONS(109),
    [anon_sym_BSLASH] = ACTIONS(109),
    [anon_sym_LBRACE] = ACTIONS(109),
    [anon_sym_RBRACE] = ACTIONS(109),
    [sym_alnum] = ACTIONS(145),
    [aux_sym_identifier_token1] = ACTIONS(145),
    [aux_sym_identifier_token2] = ACTIONS(145),
  },
  [25] = {
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(147),
    [anon_sym_RPAREN] = ACTIONS(147),
    [anon_sym_DQUOTE] = ACTIONS(147),
    [anon_sym_SQUOTE] = ACTIONS(147),
    [anon_sym_BQUOTE] = ACTIONS(147),
    [anon_sym_COMMA] = ACTIONS(147),
    [anon_sym_DOT] = ACTIONS(147),
    [anon_sym_SLASH] = ACTIONS(147),
    [anon_sym_SEMI] = ACTIONS(147),
    [anon_sym_LBRACK] = ACTIONS(147),
    [anon_sym_RBRACK] = ACTIONS(147),
    [anon_sym_BANG] = ACTIONS(147),
    [anon_sym_AT] = ACTIONS(147),
    [anon_sym_POUND] = ACTIONS(147),
    [anon_sym_DOLLAR] = ACTIONS(149),
    [anon_sym_PERCENT] = ACTIONS(147),
    [anon_sym_CARET] = ACTIONS(147),
    [anon_sym_AMP] = ACTIONS(147),
    [anon_sym_STAR] = ACTIONS(147),
    [anon_sym_LPAREN] = ACTIONS(147),
    [anon_sym_DASH] = ACTIONS(149),
    [anon_sym__] = ACTIONS(149),
    [anon_sym_EQ] = ACTIONS(147),
    [anon_sym_PLUS] = ACTIONS(147),
    [anon_sym_LT] = ACTIONS(147),
    [anon_sym_GT] = ACTIONS(147),
    [anon_sym_QMARK] = ACTIONS(147),
    [anon_sym_COLON] = ACTIONS(147),
    [anon_sym_BSLASH] = ACTIONS(147),
    [anon_sym_LBRACE] = ACTIONS(147),
    [anon_sym_RBRACE] = ACTIONS(147),
    [sym_alnum] = ACTIONS(149),
    [aux_sym_identifier_token1] = ACTIONS(149),
    [aux_sym_identifier_token2] = ACTIONS(149),
  },
  [26] = {
    [aux_sym__expression_repeat1] = STATE(36),
    [ts_builtin_sym_end] = ACTIONS(131),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(131),
    [anon_sym_RPAREN] = ACTIONS(151),
    [anon_sym_SQUOTE] = ACTIONS(151),
    [anon_sym_COMMA] = ACTIONS(151),
    [anon_sym_DOT] = ACTIONS(151),
    [anon_sym_SLASH] = ACTIONS(151),
    [anon_sym_SEMI] = ACTIONS(151),
    [anon_sym_LBRACK] = ACTIONS(151),
    [anon_sym_RBRACK] = ACTIONS(151),
    [anon_sym_BANG] = ACTIONS(151),
    [anon_sym_AT] = ACTIONS(151),
    [anon_sym_POUND] = ACTIONS(151),
    [anon_sym_DOLLAR] = ACTIONS(153),
    [anon_sym_PERCENT] = ACTIONS(151),
    [anon_sym_CARET] = ACTIONS(151),
    [anon_sym_AMP] = ACTIONS(151),
    [anon_sym_STAR] = ACTIONS(151),
    [anon_sym_LPAREN] = ACTIONS(151),
    [anon_sym_DASH] = ACTIONS(153),
    [anon_sym__] = ACTIONS(153),
    [anon_sym_EQ] = ACTIONS(151),
    [anon_sym_PLUS] = ACTIONS(151),
    [anon_sym_LT] = ACTIONS(151),
    [anon_sym_GT] = ACTIONS(151),
    [anon_sym_QMARK] = ACTIONS(151),
    [anon_sym_COLON] = ACTIONS(151),
    [anon_sym_BSLASH] = ACTIONS(151),
    [anon_sym_LBRACE] = ACTIONS(151),
    [anon_sym_RBRACE] = ACTIONS(151),
    [sym_alnum] = ACTIONS(137),
    [aux_sym_identifier_token1] = ACTIONS(137),
    [aux_sym_identifier_token2] = ACTIONS(137),
  },
  [27] = {
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(155),
    [anon_sym_RPAREN] = ACTIONS(155),
    [anon_sym_DQUOTE] = ACTIONS(155),
    [anon_sym_SQUOTE] = ACTIONS(155),
    [anon_sym_BQUOTE] = ACTIONS(155),
    [anon_sym_COMMA] = ACTIONS(155),
    [anon_sym_DOT] = ACTIONS(155),
    [anon_sym_SLASH] = ACTIONS(155),
    [anon_sym_SEMI] = ACTIONS(155),
    [anon_sym_LBRACK] = ACTIONS(155),
    [anon_sym_RBRACK] = ACTIONS(155),
    [anon_sym_BANG] = ACTIONS(155),
    [anon_sym_AT] = ACTIONS(155),
    [anon_sym_POUND] = ACTIONS(155),
    [anon_sym_DOLLAR] = ACTIONS(157),
    [anon_sym_PERCENT] = ACTIONS(155),
    [anon_sym_CARET] = ACTIONS(155),
    [anon_sym_AMP] = ACTIONS(155),
    [anon_sym_STAR] = ACTIONS(155),
    [anon_sym_LPAREN] = ACTIONS(155),
    [anon_sym_DASH] = ACTIONS(157),
    [anon_sym__] = ACTIONS(157),
    [anon_sym_EQ] = ACTIONS(155),
    [anon_sym_PLUS] = ACTIONS(155),
    [anon_sym_LT] = ACTIONS(155),
    [anon_sym_GT] = ACTIONS(155),
    [anon_sym_QMARK] = ACTIONS(155),
    [anon_sym_COLON] = ACTIONS(155),
    [anon_sym_BSLASH] = ACTIONS(155),
    [anon_sym_LBRACE] = ACTIONS(155),
    [anon_sym_RBRACE] = ACTIONS(155),
    [sym_alnum] = ACTIONS(157),
    [aux_sym_identifier_token1] = ACTIONS(157),
    [aux_sym_identifier_token2] = ACTIONS(157),
  },
  [28] = {
    [aux_sym__expression_repeat1] = STATE(32),
    [ts_builtin_sym_end] = ACTIONS(127),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(127),
    [anon_sym_RPAREN] = ACTIONS(159),
    [anon_sym_SQUOTE] = ACTIONS(159),
    [anon_sym_COMMA] = ACTIONS(159),
    [anon_sym_DOT] = ACTIONS(159),
    [anon_sym_SLASH] = ACTIONS(159),
    [anon_sym_SEMI] = ACTIONS(159),
    [anon_sym_LBRACK] = ACTIONS(159),
    [anon_sym_RBRACK] = ACTIONS(159),
    [anon_sym_BANG] = ACTIONS(159),
    [anon_sym_AT] = ACTIONS(159),
    [anon_sym_POUND] = ACTIONS(159),
    [anon_sym_DOLLAR] = ACTIONS(161),
    [anon_sym_PERCENT] = ACTIONS(159),
    [anon_sym_CARET] = ACTIONS(159),
    [anon_sym_AMP] = ACTIONS(159),
    [anon_sym_STAR] = ACTIONS(159),
    [anon_sym_LPAREN] = ACTIONS(159),
    [anon_sym_DASH] = ACTIONS(161),
    [anon_sym__] = ACTIONS(161),
    [anon_sym_EQ] = ACTIONS(159),
    [anon_sym_PLUS] = ACTIONS(159),
    [anon_sym_LT] = ACTIONS(159),
    [anon_sym_GT] = ACTIONS(159),
    [anon_sym_QMARK] = ACTIONS(159),
    [anon_sym_COLON] = ACTIONS(159),
    [anon_sym_BSLASH] = ACTIONS(159),
    [anon_sym_LBRACE] = ACTIONS(159),
    [anon_sym_RBRACE] = ACTIONS(159),
    [sym_alnum] = ACTIONS(129),
    [aux_sym_identifier_token1] = ACTIONS(129),
    [aux_sym_identifier_token2] = ACTIONS(129),
  },
  [29] = {
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(163),
    [anon_sym_RPAREN] = ACTIONS(163),
    [anon_sym_DQUOTE] = ACTIONS(163),
    [anon_sym_SQUOTE] = ACTIONS(163),
    [anon_sym_BQUOTE] = ACTIONS(163),
    [anon_sym_COMMA] = ACTIONS(163),
    [anon_sym_DOT] = ACTIONS(163),
    [anon_sym_SLASH] = ACTIONS(163),
    [anon_sym_SEMI] = ACTIONS(163),
    [anon_sym_LBRACK] = ACTIONS(163),
    [anon_sym_RBRACK] = ACTIONS(163),
    [anon_sym_BANG] = ACTIONS(163),
    [anon_sym_AT] = ACTIONS(163),
    [anon_sym_POUND] = ACTIONS(163),
    [anon_sym_DOLLAR] = ACTIONS(165),
    [anon_sym_PERCENT] = ACTIONS(163),
    [anon_sym_CARET] = ACTIONS(163),
    [anon_sym_AMP] = ACTIONS(163),
    [anon_sym_STAR] = ACTIONS(163),
    [anon_sym_LPAREN] = ACTIONS(163),
    [anon_sym_DASH] = ACTIONS(165),
    [anon_sym__] = ACTIONS(165),
    [anon_sym_EQ] = ACTIONS(163),
    [anon_sym_PLUS] = ACTIONS(163),
    [anon_sym_LT] = ACTIONS(163),
    [anon_sym_GT] = ACTIONS(163),
    [anon_sym_QMARK] = ACTIONS(163),
    [anon_sym_COLON] = ACTIONS(163),
    [anon_sym_BSLASH] = ACTIONS(163),
    [anon_sym_LBRACE] = ACTIONS(163),
    [anon_sym_RBRACE] = ACTIONS(163),
    [sym_alnum] = ACTIONS(165),
    [aux_sym_identifier_token1] = ACTIONS(165),
    [aux_sym_identifier_token2] = ACTIONS(165),
  },
  [30] = {
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(155),
    [anon_sym_RPAREN] = ACTIONS(155),
    [anon_sym_DQUOTE] = ACTIONS(155),
    [anon_sym_SQUOTE] = ACTIONS(155),
    [anon_sym_BQUOTE] = ACTIONS(155),
    [anon_sym_COMMA] = ACTIONS(155),
    [anon_sym_DOT] = ACTIONS(155),
    [anon_sym_SLASH] = ACTIONS(155),
    [anon_sym_SEMI] = ACTIONS(155),
    [anon_sym_LBRACK] = ACTIONS(155),
    [anon_sym_RBRACK] = ACTIONS(155),
    [anon_sym_BANG] = ACTIONS(155),
    [anon_sym_AT] = ACTIONS(155),
    [anon_sym_POUND] = ACTIONS(155),
    [anon_sym_DOLLAR] = ACTIONS(157),
    [anon_sym_PERCENT] = ACTIONS(155),
    [anon_sym_CARET] = ACTIONS(155),
    [anon_sym_AMP] = ACTIONS(155),
    [anon_sym_STAR] = ACTIONS(155),
    [anon_sym_LPAREN] = ACTIONS(155),
    [anon_sym_DASH] = ACTIONS(157),
    [anon_sym__] = ACTIONS(157),
    [anon_sym_EQ] = ACTIONS(155),
    [anon_sym_PLUS] = ACTIONS(155),
    [anon_sym_LT] = ACTIONS(155),
    [anon_sym_GT] = ACTIONS(155),
    [anon_sym_QMARK] = ACTIONS(155),
    [anon_sym_COLON] = ACTIONS(155),
    [anon_sym_BSLASH] = ACTIONS(155),
    [anon_sym_LBRACE] = ACTIONS(155),
    [anon_sym_RBRACE] = ACTIONS(155),
    [sym_alnum] = ACTIONS(157),
    [aux_sym_identifier_token1] = ACTIONS(157),
    [aux_sym_identifier_token2] = ACTIONS(157),
  },
  [31] = {
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(167),
    [anon_sym_RPAREN] = ACTIONS(167),
    [anon_sym_DQUOTE] = ACTIONS(167),
    [anon_sym_SQUOTE] = ACTIONS(167),
    [anon_sym_BQUOTE] = ACTIONS(167),
    [anon_sym_COMMA] = ACTIONS(167),
    [anon_sym_DOT] = ACTIONS(167),
    [anon_sym_SLASH] = ACTIONS(167),
    [anon_sym_SEMI] = ACTIONS(167),
    [anon_sym_LBRACK] = ACTIONS(167),
    [anon_sym_RBRACK] = ACTIONS(167),
    [anon_sym_BANG] = ACTIONS(167),
    [anon_sym_AT] = ACTIONS(167),
    [anon_sym_POUND] = ACTIONS(167),
    [anon_sym_DOLLAR] = ACTIONS(169),
    [anon_sym_PERCENT] = ACTIONS(167),
    [anon_sym_CARET] = ACTIONS(167),
    [anon_sym_AMP] = ACTIONS(167),
    [anon_sym_STAR] = ACTIONS(167),
    [anon_sym_LPAREN] = ACTIONS(167),
    [anon_sym_DASH] = ACTIONS(169),
    [anon_sym__] = ACTIONS(169),
    [anon_sym_EQ] = ACTIONS(167),
    [anon_sym_PLUS] = ACTIONS(167),
    [anon_sym_LT] = ACTIONS(167),
    [anon_sym_GT] = ACTIONS(167),
    [anon_sym_QMARK] = ACTIONS(167),
    [anon_sym_COLON] = ACTIONS(167),
    [anon_sym_BSLASH] = ACTIONS(167),
    [anon_sym_LBRACE] = ACTIONS(167),
    [anon_sym_RBRACE] = ACTIONS(167),
    [sym_alnum] = ACTIONS(169),
    [aux_sym_identifier_token1] = ACTIONS(169),
    [aux_sym_identifier_token2] = ACTIONS(169),
  },
  [32] = {
    [aux_sym__expression_repeat1] = STATE(35),
    [ts_builtin_sym_end] = ACTIONS(143),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(143),
    [anon_sym_RPAREN] = ACTIONS(171),
    [anon_sym_SQUOTE] = ACTIONS(171),
    [anon_sym_COMMA] = ACTIONS(171),
    [anon_sym_DOT] = ACTIONS(171),
    [anon_sym_SLASH] = ACTIONS(171),
    [anon_sym_SEMI] = ACTIONS(171),
    [anon_sym_LBRACK] = ACTIONS(171),
    [anon_sym_RBRACK] = ACTIONS(171),
    [anon_sym_BANG] = ACTIONS(171),
    [anon_sym_AT] = ACTIONS(171),
    [anon_sym_POUND] = ACTIONS(171),
    [anon_sym_DOLLAR] = ACTIONS(173),
    [anon_sym_PERCENT] = ACTIONS(171),
    [anon_sym_CARET] = ACTIONS(171),
    [anon_sym_AMP] = ACTIONS(171),
    [anon_sym_STAR] = ACTIONS(171),
    [anon_sym_LPAREN] = ACTIONS(171),
    [anon_sym_DASH] = ACTIONS(173),
    [anon_sym__] = ACTIONS(173),
    [anon_sym_EQ] = ACTIONS(171),
    [anon_sym_PLUS] = ACTIONS(171),
    [anon_sym_LT] = ACTIONS(171),
    [anon_sym_GT] = ACTIONS(171),
    [anon_sym_QMARK] = ACTIONS(171),
    [anon_sym_COLON] = ACTIONS(171),
    [anon_sym_BSLASH] = ACTIONS(171),
    [anon_sym_LBRACE] = ACTIONS(171),
    [anon_sym_RBRACE] = ACTIONS(171),
    [sym_alnum] = ACTIONS(145),
    [aux_sym_identifier_token1] = ACTIONS(145),
    [aux_sym_identifier_token2] = ACTIONS(145),
  },
  [33] = {
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(175),
    [anon_sym_RPAREN] = ACTIONS(175),
    [anon_sym_DQUOTE] = ACTIONS(175),
    [anon_sym_SQUOTE] = ACTIONS(175),
    [anon_sym_BQUOTE] = ACTIONS(175),
    [anon_sym_COMMA] = ACTIONS(175),
    [anon_sym_DOT] = ACTIONS(175),
    [anon_sym_SLASH] = ACTIONS(175),
    [anon_sym_SEMI] = ACTIONS(175),
    [anon_sym_LBRACK] = ACTIONS(175),
    [anon_sym_RBRACK] = ACTIONS(175),
    [anon_sym_BANG] = ACTIONS(175),
    [anon_sym_AT] = ACTIONS(175),
    [anon_sym_POUND] = ACTIONS(175),
    [anon_sym_DOLLAR] = ACTIONS(177),
    [anon_sym_PERCENT] = ACTIONS(175),
    [anon_sym_CARET] = ACTIONS(175),
    [anon_sym_AMP] = ACTIONS(175),
    [anon_sym_STAR] = ACTIONS(175),
    [anon_sym_LPAREN] = ACTIONS(175),
    [anon_sym_DASH] = ACTIONS(177),
    [anon_sym__] = ACTIONS(177),
    [anon_sym_EQ] = ACTIONS(175),
    [anon_sym_PLUS] = ACTIONS(175),
    [anon_sym_LT] = ACTIONS(175),
    [anon_sym_GT] = ACTIONS(175),
    [anon_sym_QMARK] = ACTIONS(175),
    [anon_sym_COLON] = ACTIONS(175),
    [anon_sym_BSLASH] = ACTIONS(175),
    [anon_sym_LBRACE] = ACTIONS(175),
    [anon_sym_RBRACE] = ACTIONS(175),
    [sym_alnum] = ACTIONS(177),
    [aux_sym_identifier_token1] = ACTIONS(177),
    [aux_sym_identifier_token2] = ACTIONS(177),
  },
  [34] = {
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(175),
    [anon_sym_RPAREN] = ACTIONS(175),
    [anon_sym_DQUOTE] = ACTIONS(175),
    [anon_sym_SQUOTE] = ACTIONS(175),
    [anon_sym_BQUOTE] = ACTIONS(175),
    [anon_sym_COMMA] = ACTIONS(175),
    [anon_sym_DOT] = ACTIONS(175),
    [anon_sym_SLASH] = ACTIONS(175),
    [anon_sym_SEMI] = ACTIONS(175),
    [anon_sym_LBRACK] = ACTIONS(175),
    [anon_sym_RBRACK] = ACTIONS(175),
    [anon_sym_BANG] = ACTIONS(175),
    [anon_sym_AT] = ACTIONS(175),
    [anon_sym_POUND] = ACTIONS(175),
    [anon_sym_DOLLAR] = ACTIONS(177),
    [anon_sym_PERCENT] = ACTIONS(175),
    [anon_sym_CARET] = ACTIONS(175),
    [anon_sym_AMP] = ACTIONS(175),
    [anon_sym_STAR] = ACTIONS(175),
    [anon_sym_LPAREN] = ACTIONS(175),
    [anon_sym_DASH] = ACTIONS(177),
    [anon_sym__] = ACTIONS(177),
    [anon_sym_EQ] = ACTIONS(175),
    [anon_sym_PLUS] = ACTIONS(175),
    [anon_sym_LT] = ACTIONS(175),
    [anon_sym_GT] = ACTIONS(175),
    [anon_sym_QMARK] = ACTIONS(175),
    [anon_sym_COLON] = ACTIONS(175),
    [anon_sym_BSLASH] = ACTIONS(175),
    [anon_sym_LBRACE] = ACTIONS(175),
    [anon_sym_RBRACE] = ACTIONS(175),
    [sym_alnum] = ACTIONS(177),
    [aux_sym_identifier_token1] = ACTIONS(177),
    [aux_sym_identifier_token2] = ACTIONS(177),
  },
  [35] = {
    [aux_sym__expression_repeat1] = STATE(35),
    [ts_builtin_sym_end] = ACTIONS(117),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(117),
    [anon_sym_RPAREN] = ACTIONS(179),
    [anon_sym_SQUOTE] = ACTIONS(179),
    [anon_sym_COMMA] = ACTIONS(179),
    [anon_sym_DOT] = ACTIONS(179),
    [anon_sym_SLASH] = ACTIONS(179),
    [anon_sym_SEMI] = ACTIONS(179),
    [anon_sym_LBRACK] = ACTIONS(179),
    [anon_sym_RBRACK] = ACTIONS(179),
    [anon_sym_BANG] = ACTIONS(179),
    [anon_sym_AT] = ACTIONS(179),
    [anon_sym_POUND] = ACTIONS(179),
    [anon_sym_DOLLAR] = ACTIONS(182),
    [anon_sym_PERCENT] = ACTIONS(179),
    [anon_sym_CARET] = ACTIONS(179),
    [anon_sym_AMP] = ACTIONS(179),
    [anon_sym_STAR] = ACTIONS(179),
    [anon_sym_LPAREN] = ACTIONS(179),
    [anon_sym_DASH] = ACTIONS(182),
    [anon_sym__] = ACTIONS(182),
    [anon_sym_EQ] = ACTIONS(179),
    [anon_sym_PLUS] = ACTIONS(179),
    [anon_sym_LT] = ACTIONS(179),
    [anon_sym_GT] = ACTIONS(179),
    [anon_sym_QMARK] = ACTIONS(179),
    [anon_sym_COLON] = ACTIONS(179),
    [anon_sym_BSLASH] = ACTIONS(179),
    [anon_sym_LBRACE] = ACTIONS(179),
    [anon_sym_RBRACE] = ACTIONS(179),
    [sym_alnum] = ACTIONS(125),
    [aux_sym_identifier_token1] = ACTIONS(125),
    [aux_sym_identifier_token2] = ACTIONS(125),
  },
  [36] = {
    [aux_sym__expression_repeat1] = STATE(35),
    [ts_builtin_sym_end] = ACTIONS(127),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(127),
    [anon_sym_RPAREN] = ACTIONS(171),
    [anon_sym_SQUOTE] = ACTIONS(171),
    [anon_sym_COMMA] = ACTIONS(171),
    [anon_sym_DOT] = ACTIONS(171),
    [anon_sym_SLASH] = ACTIONS(171),
    [anon_sym_SEMI] = ACTIONS(171),
    [anon_sym_LBRACK] = ACTIONS(171),
    [anon_sym_RBRACK] = ACTIONS(171),
    [anon_sym_BANG] = ACTIONS(171),
    [anon_sym_AT] = ACTIONS(171),
    [anon_sym_POUND] = ACTIONS(171),
    [anon_sym_DOLLAR] = ACTIONS(173),
    [anon_sym_PERCENT] = ACTIONS(171),
    [anon_sym_CARET] = ACTIONS(171),
    [anon_sym_AMP] = ACTIONS(171),
    [anon_sym_STAR] = ACTIONS(171),
    [anon_sym_LPAREN] = ACTIONS(171),
    [anon_sym_DASH] = ACTIONS(173),
    [anon_sym__] = ACTIONS(173),
    [anon_sym_EQ] = ACTIONS(171),
    [anon_sym_PLUS] = ACTIONS(171),
    [anon_sym_LT] = ACTIONS(171),
    [anon_sym_GT] = ACTIONS(171),
    [anon_sym_QMARK] = ACTIONS(171),
    [anon_sym_COLON] = ACTIONS(171),
    [anon_sym_BSLASH] = ACTIONS(171),
    [anon_sym_LBRACE] = ACTIONS(171),
    [anon_sym_RBRACE] = ACTIONS(171),
    [sym_alnum] = ACTIONS(129),
    [aux_sym_identifier_token1] = ACTIONS(129),
    [aux_sym_identifier_token2] = ACTIONS(129),
  },
  [37] = {
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(185),
    [anon_sym_RPAREN] = ACTIONS(185),
    [anon_sym_DQUOTE] = ACTIONS(185),
    [anon_sym_SQUOTE] = ACTIONS(185),
    [anon_sym_BQUOTE] = ACTIONS(185),
    [anon_sym_COMMA] = ACTIONS(185),
    [anon_sym_DOT] = ACTIONS(185),
    [anon_sym_SLASH] = ACTIONS(185),
    [anon_sym_SEMI] = ACTIONS(185),
    [anon_sym_LBRACK] = ACTIONS(185),
    [anon_sym_RBRACK] = ACTIONS(185),
    [anon_sym_BANG] = ACTIONS(185),
    [anon_sym_AT] = ACTIONS(185),
    [anon_sym_POUND] = ACTIONS(185),
    [anon_sym_DOLLAR] = ACTIONS(187),
    [anon_sym_PERCENT] = ACTIONS(185),
    [anon_sym_CARET] = ACTIONS(185),
    [anon_sym_AMP] = ACTIONS(185),
    [anon_sym_STAR] = ACTIONS(185),
    [anon_sym_LPAREN] = ACTIONS(185),
    [anon_sym_DASH] = ACTIONS(187),
    [anon_sym__] = ACTIONS(187),
    [anon_sym_EQ] = ACTIONS(185),
    [anon_sym_PLUS] = ACTIONS(185),
    [anon_sym_LT] = ACTIONS(185),
    [anon_sym_GT] = ACTIONS(185),
    [anon_sym_QMARK] = ACTIONS(185),
    [anon_sym_COLON] = ACTIONS(185),
    [anon_sym_BSLASH] = ACTIONS(185),
    [anon_sym_LBRACE] = ACTIONS(185),
    [anon_sym_RBRACE] = ACTIONS(185),
    [sym_alnum] = ACTIONS(187),
    [aux_sym_identifier_token1] = ACTIONS(187),
    [aux_sym_identifier_token2] = ACTIONS(187),
  },
  [38] = {
    [ts_builtin_sym_end] = ACTIONS(185),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(185),
    [anon_sym_RPAREN] = ACTIONS(185),
    [anon_sym_SQUOTE] = ACTIONS(185),
    [anon_sym_COMMA] = ACTIONS(185),
    [anon_sym_DOT] = ACTIONS(185),
    [anon_sym_SLASH] = ACTIONS(185),
    [anon_sym_SEMI] = ACTIONS(185),
    [anon_sym_LBRACK] = ACTIONS(185),
    [anon_sym_RBRACK] = ACTIONS(185),
    [anon_sym_BANG] = ACTIONS(185),
    [anon_sym_AT] = ACTIONS(185),
    [anon_sym_POUND] = ACTIONS(185),
    [anon_sym_DOLLAR] = ACTIONS(187),
    [anon_sym_PERCENT] = ACTIONS(185),
    [anon_sym_CARET] = ACTIONS(185),
    [anon_sym_AMP] = ACTIONS(185),
    [anon_sym_STAR] = ACTIONS(185),
    [anon_sym_LPAREN] = ACTIONS(185),
    [anon_sym_DASH] = ACTIONS(187),
    [anon_sym__] = ACTIONS(187),
    [anon_sym_EQ] = ACTIONS(185),
    [anon_sym_PLUS] = ACTIONS(185),
    [anon_sym_LT] = ACTIONS(185),
    [anon_sym_GT] = ACTIONS(185),
    [anon_sym_QMARK] = ACTIONS(185),
    [anon_sym_COLON] = ACTIONS(185),
    [anon_sym_BSLASH] = ACTIONS(185),
    [anon_sym_LBRACE] = ACTIONS(185),
    [anon_sym_RBRACE] = ACTIONS(185),
    [sym_alnum] = ACTIONS(187),
    [aux_sym_identifier_token1] = ACTIONS(187),
    [aux_sym_identifier_token2] = ACTIONS(187),
  },
  [39] = {
    [ts_builtin_sym_end] = ACTIONS(147),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(147),
    [anon_sym_RPAREN] = ACTIONS(147),
    [anon_sym_SQUOTE] = ACTIONS(147),
    [anon_sym_COMMA] = ACTIONS(147),
    [anon_sym_DOT] = ACTIONS(147),
    [anon_sym_SLASH] = ACTIONS(147),
    [anon_sym_SEMI] = ACTIONS(147),
    [anon_sym_LBRACK] = ACTIONS(147),
    [anon_sym_RBRACK] = ACTIONS(147),
    [anon_sym_BANG] = ACTIONS(147),
    [anon_sym_AT] = ACTIONS(147),
    [anon_sym_POUND] = ACTIONS(147),
    [anon_sym_DOLLAR] = ACTIONS(149),
    [anon_sym_PERCENT] = ACTIONS(147),
    [anon_sym_CARET] = ACTIONS(147),
    [anon_sym_AMP] = ACTIONS(147),
    [anon_sym_STAR] = ACTIONS(147),
    [anon_sym_LPAREN] = ACTIONS(147),
    [anon_sym_DASH] = ACTIONS(149),
    [anon_sym__] = ACTIONS(149),
    [anon_sym_EQ] = ACTIONS(147),
    [anon_sym_PLUS] = ACTIONS(147),
    [anon_sym_LT] = ACTIONS(147),
    [anon_sym_GT] = ACTIONS(147),
    [anon_sym_QMARK] = ACTIONS(147),
    [anon_sym_COLON] = ACTIONS(147),
    [anon_sym_BSLASH] = ACTIONS(147),
    [anon_sym_LBRACE] = ACTIONS(147),
    [anon_sym_RBRACE] = ACTIONS(147),
    [sym_alnum] = ACTIONS(149),
    [aux_sym_identifier_token1] = ACTIONS(149),
    [aux_sym_identifier_token2] = ACTIONS(149),
  },
  [40] = {
    [ts_builtin_sym_end] = ACTIONS(163),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(163),
    [anon_sym_RPAREN] = ACTIONS(163),
    [anon_sym_SQUOTE] = ACTIONS(163),
    [anon_sym_COMMA] = ACTIONS(163),
    [anon_sym_DOT] = ACTIONS(163),
    [anon_sym_SLASH] = ACTIONS(163),
    [anon_sym_SEMI] = ACTIONS(163),
    [anon_sym_LBRACK] = ACTIONS(163),
    [anon_sym_RBRACK] = ACTIONS(163),
    [anon_sym_BANG] = ACTIONS(163),
    [anon_sym_AT] = ACTIONS(163),
    [anon_sym_POUND] = ACTIONS(163),
    [anon_sym_DOLLAR] = ACTIONS(165),
    [anon_sym_PERCENT] = ACTIONS(163),
    [anon_sym_CARET] = ACTIONS(163),
    [anon_sym_AMP] = ACTIONS(163),
    [anon_sym_STAR] = ACTIONS(163),
    [anon_sym_LPAREN] = ACTIONS(163),
    [anon_sym_DASH] = ACTIONS(165),
    [anon_sym__] = ACTIONS(165),
    [anon_sym_EQ] = ACTIONS(163),
    [anon_sym_PLUS] = ACTIONS(163),
    [anon_sym_LT] = ACTIONS(163),
    [anon_sym_GT] = ACTIONS(163),
    [anon_sym_QMARK] = ACTIONS(163),
    [anon_sym_COLON] = ACTIONS(163),
    [anon_sym_BSLASH] = ACTIONS(163),
    [anon_sym_LBRACE] = ACTIONS(163),
    [anon_sym_RBRACE] = ACTIONS(163),
    [sym_alnum] = ACTIONS(165),
    [aux_sym_identifier_token1] = ACTIONS(165),
    [aux_sym_identifier_token2] = ACTIONS(165),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    STATE(4), 1,
      sym_identifier,
    ACTIONS(189), 2,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
  [8] = 2,
    STATE(6), 1,
      sym_identifier,
    ACTIONS(189), 2,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
  [16] = 1,
    ACTIONS(191), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(41)] = 0,
  [SMALL_STATE(42)] = 8,
  [SMALL_STATE(43)] = 16,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input, 2, 0, 0),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [98] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_input_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__expression_repeat1, 2, 0, 0),
  [119] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expression_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [122] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expression_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__expression_repeat1, 2, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 3, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, 0, 1),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 3, 0, 1),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 2, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 2, 0, 0),
  [179] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expression_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [182] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expression_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 4, 0, 2),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 4, 0, 2),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [191] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_akbs(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
